.gitignore
legend-pure-ide-light/src/main/web/README.md
legend-pure-ide-light/src/main/web/package-lock.json
legend-pure-ide-light/src/main/web/package.json
legend-pure-ide-light/src/main/web/src/components/editor/edit-panel/FileEditor.tsx
legend-pure-ide-light/src/main/web/src/stores/ConceptTreeState.ts
legend-pure-ide-light/src/main/web/src/stores/EditorStore.tsx
legend-pure-ide-light/src/main/web/src/stores/TestRunnerState.ts
legend-pure-ide-light/src/main/web/src/utils/GeneralUtil.ts
pom.xml

@aziemchawdhary-gs @kevin-m-knight-gs @pierredebelen it seems like the `dropwizard` and `jetty` upgrade in #36 breaks execution in the IDE. I tried to execute something that takes a long time like `[1:10000]->map(i|print($i);` and the IDE returns me an error. Could you confirm that @aziemchawdhary-gs?
This will certainly make `whitesource` scream, but we might need to workaround that somehow, `dropwizard` is still taking sometimes to port their fix in https://github.com/dropwizard/dropwizard/pull/3522 (and https://github.com/dropwizard/dropwizard/pull/3527) to v1.3.x so we might not be able to wait. I reckon that the best way is to revert this for now. What do you guys think?

revert dropwizard and jetty upgrade and improve IDE execution perceived performance

---

legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/binary/DistributedBinaryGraphDeserializer.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/binary/SourceCoordinateMapProvider.java

Allow for injection of custom source coordinate mapping providers that (for example) don't use on-heap memory.

Allow for injection of custom source coordinate mapping providers

---

legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetch.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/testExplosion.pure

Identified a bug in java code gen flow. It effects graph queries working on mapping having sets with and without explosion property mapping

fix java code gen bug

---

legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/mappingAdaptor.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/testExplosion.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/shared.pure

Encountered a bug in java code gen flow. Bug impacts graphfetch queries where explosion mapping is used at a property level or explosion mapping is used on date properties

fix java code gen explosion bug

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/validation/validator/ElementWithConstraintsValidator.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/validation/validator/FunctionDefinitionValidator.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/constraints/AbstractTestConstraints.java

Fixes the Pure compiler to type check lambdas in constraint definitions (both function and message lambdas).

Check function expressions in constraints

---

legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testRouting.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/simple.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure

A bug was identified in routing flow. It impacts non-relational store use cases when there are multiple class mappings for same class

fix routing for multiple class mappings

---

legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/mappingExtension.pure

Reverting back to previous implementation to fix builds. This change led to change in ordering of result list

Revert back to previous implementation to fix builds

---

legend-pure-code-compiled-core/pom.xml
legend-pure-code-compiled-core/src/test/java/org/finos/legend/pure/code/core/TestCoreCompiledStateIntegrity.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/functionmatch/FunctionExpressionMatcher.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/valuespecification/FunctionExpressionProcessor.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/_class/_Class.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/lineinfo/TestLineInfo.java
legend-pure-m3-dsl-graph/src/main/java/org/finos/legend/pure/m3/inlinedsl/graph/processor/RootGraphFetchTreeProcessor.java

Two of the integrity tests are currently failing and so are ignored. They need to be fixed. But the rest of the tests still have value, so I think it's worthwhile to merge the test in. And the ignored tests can be used as a guide for what needs to be fixed (the single biggest one being the reference usages for graph fetch trees).

Initial compiled state integrity test for core

---

legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/graphFetchCommon.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchInMemory.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/constraints.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/simpleObject.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure

Allow unmapped properties to be used in constraints and not cause defects if the expression does not access the property (for example in an if).

Allow unmapped properties to be used in constraints

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/aggregationAware/test/mapping.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/aggregationAware/test/rewrite/objectGroupBy.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/aggregationAware/aggregationAware.pure

This is fix for an error that originally was spotted during plan generation when we use more than one agg() function in the query

Allow multiple aggregates in query

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/pushFiltersDownToJoin.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/postprocessor/defaultPostProcessor/reAliasQuery.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/postprocessor/postProcessor.pure

It was found out that executing default post processors is taking lot of time. This change helps in improving time efficiency of default post processors flow

refactoring postProcessor flow to improve time efficiency

---

legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/main.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/typeInfo.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/constraints.pure

Refine computation of classes that are prohibited from having new instances created explicitly via the new operator.
This changeset refines the computation of which classes should be prohibited from having new instances created explicitly via the new operator (in constraints for example) to be more self-contained within typeInfo computation and not rely on incorrect assumptions on how class type information is computed in the M2M generation. 
This also fixes a bug where classes were not being generated for property chains starting at a qualified property and resulting in compilation failures during plan generation.

M2M: Refine computation of prohibited classes for new operator

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tests/mapping/sqlFunction/testSqlFunctionsInMapping.pure

This new functionality is to get the difference between two dates in the SECONDS dimension for Memsql

Improve the dateDiff function to support SECONDS for memsql

---

legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/metamodel.pure

Remove parameters of the MessageFunction in the Constraint to avoid invalid tokens in the grammar generated from the pure model context data that is generated from Pure

Remove parameters of the MessageFunction in the Constraint

---

legend-pure-ide-light/src/main/web/src/components/editor/edit-panel/FileEditor.tsx

Stop the browser catching default keybindings defined in the IDE Light text editor (e.g. ctrl+b opens the bookmark panel in Firefox)

IDE Light: override browser keybinding defaults

---

legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/main.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/typeInfo.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/constraints.pure

Expand support for where new is supported: allow use of new in qualified properties provided the return type of the qualified property is primitive. This prevents the use of new to create instances as the result of mapping but allows the creation of ephemeral data for use in validations during mapping execution.

Java M2M: Add support for calling new from qualified properties

---

legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testSourceTreeCalc.pure

When computing properties to include in the source tree we need to make sure that we only include properties that are part of the current class being processed. 
This fix adds validation and filters to ensure that we only include the relevant properties based on the current class being processed.

Graphfetch: validate property owners when computing sourceTree

---

legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/collections/testAt.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/collections/testIndexOf.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/collectionsLibrary.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/collectionsLibraryTests.pure

Support at(0)/indexOf on properties with [1] or [0..1] in execution plan.
Need to be released with this commit together.  https://github.com/finos/legend-engine/pull/350

Support at(0)/indexOf on properties with [1] or [0..1] in execution plan

---

legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/simpleObject.pure

There was a typo in the subType test for m2m

Fix typo in subType test

---

legend-pure-code-compiled-core/src/main/resources/core/pure/dataSpace/dataSpace.pure

This is needed for for SDLC to pick up this new type of element

add stubbed DataSpace packageable element

---

legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testSourceTreeCalc.pure

If a class has property accesses to both its own properties and properties of a supertype then the fetch tree generated has distinct subtrees to represent the subtype and supertype accesses. This is so that we can disambiguate which class the property access is on when performing code generation.
However, the tree merging code assumes that there is a single subTree for each property and will fail if there is more than one subtree.
This fix changes the merging to handle multiple subtrees for the same property.

Fix tree merging to handle fetchtrees with more than one subtree

---

legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Pure.java

`ClassNotFoundException` can occur when we use `subTypeOf()` in `engine` where some Java classes are not available during plan generation. There is a _potentially_ less performant alternative which is to use `type_subTypeOf()` as this will use the metamodel graph instead of Java classes to test subtype; but this alternative is more reliable. As such, to be defensive, we should fallback to the latter when the former fails with `ClassNotFoundException`
Full context could be found in https://github.com/finos/legend-pure/issues/324
---
---
Closes https://github.com/finos/legend-pure/issues/324
@kevin-m-knight-gs Could you kindly take a look at this?

handle `ClassNotFoundException` in `subTypeOf()`

---

legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/graphFetchCommon.pure

This PR makes the code generated graph fetch node classes serializable.
Changes to code generation:
- All graph fetch node classes implement java.io.Serializable
- A serialVersionUID is computed and added to each graph fetch node class

Make graph fetch node classes serializable

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelations.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelationsTests.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tests/mapping/union/testUnion.pure

Impact
- Users are not able to generate test data easily for use-case where union is defined on same table with different keys
- Pure/Engine cannot generate relation tree lineage for above use-case

Fix bug impacting use-cases where union is defined on same table with different keys

---

legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/assertLibrary.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/simpleObject.pure

**Functional change:**
Add missing assert functions to Java code generator: this avoids having to translate the definitions of these assert functions and instead relies on the hard-coded translation defined in the assertLibrary. 
There is a bug in Pure, where the Java code generator picks up the wrong body when translating some assert functions - this means that we generate Java code which does not compile.
**Tests**
Two tests added in this change to ensure that we compile asserts correctly in execution plans

Add missing asserts to Java-gen to avoid translating their definition

---

legend-pure-code-java-compiled-core/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/TestIdBuilderCore.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/runtime/TestIncrementalCompiler.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/TestFunction.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tools/TestGraphPath.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaSourceCodeGenerator.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/ProcessorContext.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/IdBuilder.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Pure.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataLazy.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/TestMeasureCompiled.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/constraints/TestConstraintHandlerCompiled.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/constraints/TestConstraints.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/TestIdBuilder.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/asserts/TestAssert.java
legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/incremental/TestSyntheticNodeCut.java

Fix the compiled mode metadata id for lambda functions to ensure that it is unique. Previously, the same id could be generated for different lambdas under certain circumstances.
For example, the lambda at:
https://github.com/finos/legend-pure/blob/82e3cadb2934122537e0c24d307b76b5676aac45/legend-pure-m3-platform/src/main/resources/platform/pure/corefunctions/test.pure#L22
would have previously been given the same id as the lambda at:
https://github.com/finos/legend-pure/blob/82e3cadb2934122537e0c24d307b76b5676aac45/legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/testExtension.pure#L26
This is no longer the case.

Fix metadata id for lambda functions

---

legend-pure-code-compiled-core-external-format-flatdata/src/main/resources/core_external_format_flatdata/executionPlan/executionPlan.pure
legend-pure-code-compiled-core-external-format-json/src/main/resources/core_external_format_json/executionPlan/executionPlan.pure
legend-pure-code-compiled-core-external-format-json/src/main/resources/core_external_format_json/executionPlan/javaRuntime/executionPlanNodes/jsonDeserialize/jsonDeserialize.pure
legend-pure-code-compiled-core-external-format-json/src/main/resources/core_external_format_json/extension.pure
legend-pure-code-compiled-core-external-format-json/src/main/resources/core_external_format_json/protocols/pure/vX_X_X/models/executionPlan_external_format_json.pure
legend-pure-code-compiled-core-external-format-json/src/main/resources/core_external_format_json/protocols/pure/vX_X_X/transfers/executionPlan_external_format_json.pure
legend-pure-code-compiled-core-external-format-xml/src/main/resources/core_external_format_xml/executionPlan/executionPlan.pure
legend-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/executionPlan/executionPlan.pure
legend-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/executionPlan/model.pure
legend-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/extension.pure
legend-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/extensions/extension.pure
legend-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/protocol_vX_X_X.pure
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/executionPlan/executionPlan_generation.pure
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/metamodel/serviceStoreMapping.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/executionNode/graphFetch/inMemory/graphFetchJson.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/jacksonSupport.pure

There have been use-cases reported where users have their required data wrapped around with some metadata.
In such scenario's people have had to model wrapped structure & then flatten out the response in mapping. This has following disadvantages - 
1. For Json we read input stream node by node but since in this scenario users data had been wrapped we ended up realizing entire data at once.
2. Flattening of wrapped models to required models is not easy (requires effort) and has lot of restrictions (currently explosion operator is used for flattening)
This PR changes help users define the subsection path/offset from where we should start deserializing the contents of the stream. This helps resolve above 2 disadvantages

Add support for reading subsection of service response

---

legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/date/testAdjustDate.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/simpleObject.pure
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/AbstractDateWithDay.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/AbstractDateWithHour.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/AbstractDateWithMinute.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/AbstractDateWithSecond.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/AbstractDateWithSubsecond.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/DateWithHour.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/DateWithMinute.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/DateWithSecond.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/LatestDate.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/PureDate.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/StrictDate.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/Year.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/YearMonth.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CompiledSupport.java
legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/core/date/AdjustDate.java

Change adjustDate to use long for computations with microseconds.
Tests added at legend-pure language level and for mapping execution against legend-engine

Fix adjustDate to use long for microseconds

---

legend-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/executionPlan/executionPlan_diagram.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/executionPlan/executionPlan_diagram.pure
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/executionPlan/executionPlan_diagram.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/executionPlan_diagram.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/executionPlan_diagram.pure

Added below diagrams for execution plan metamodel (spread across different core repositories):

Add execution plan diagrams

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/transform/fromPure/tests/testToSQLString.pure

For databases which do not support conditional expressions in select columns, it is necessary to wrap such conditional expressions in case statements. Adding isDistinct function to boolean returning dyna function list will ensure that case statement generation happens.

Add isDistinct to boolean returning dyna function list

---

legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/metamodel/serviceStore.pure
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/protocols/pure/vX_X_X/models/metamodel_serviceStore.pure
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/protocols/pure/vX_X_X/transfers/metamodel_serviceStore.pure

Add support for allow reserved config for service parameters - https://swagger.io/docs/specification/describing-parameters/

Add support for allow reserved config for service parameters.

---

legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Pure.java
pom.xml

Require Java 11.0.13 or higher for legend-pure builds. This version of Java contains a fix for this bug:
https://bugs.openjdk.java.net/browse/JDK-8210495
Also, remove a workaround for that bug.

Require Java 11.0.13 or higher

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/validation/VisibilityValidation.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/validation/validator/ClassValidator.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/validation/validator/ProfileValidator.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/M3AntlrParser.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/validation/TestProfileValidation.java

Add validation to ensure a profile does not have name clashes among stereotypes or tags. Specifically, if there are multiple stereotypes with the same name or multiple tags with the same name, this validation will throw a PureCompilationException. (The name spaces for tags and stereotypes are separate, so there may be a stereotype with the same name as a tag.)

Annotation validation

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/IncrementalCompiler_New.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/GraphPath.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/PackageTreeIterable.java

Fix a bug in the start node path regex detected by Sonar.
Also, explicitly throw NoSuchElementException in PackageTreeIterable so that Sonar will no longer complain. This would have been thrown already, though via a call to Deque.removeFirst.
Also, simplify some logic in IncrementalCompiler_New so that (hopefully) Sonar will understand when repoTransaction is not null.

Bug fixes for Sonar

---

legend-pure-m2-dsl-mapping/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/antlr/AggregationAwareGraphBuilder.java

The parser for aggregation aware mappings was in some cases assigning duplicate ids to lambda functions. This fixes that.

Fix bug with assigning lambda ids in aggregation aware mappings

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery_union.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tests/mapping/union/testUnion.pure

When loading result of a union query into a table, we need to define a pk. That pk can be defined as union of pks of individual tables within union. Problem here is that null isn't allowed in pk, but union query exports null for pk cols which are not present in source tables. The fix in this PR is to export default values instead of null, when importDataFlow is enabled.

Export default literal values for pk cols in union dataflow

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/transform/fromPure/tests/testToSQLString.pure

Snowflake CHARINDEX function expects the string to look for as the first parameter and string to search in as the second parameter. Currently, parameters are being generated in the reverse order.
Reference: https://docs.snowflake.com/en/sql-reference/functions/charindex.html#varchar-expressions

Fix Snowflake indexOf SQL translation

---

legend-pure-m2-dsl-mapping/src/main/resources/platform/pure/mapping.pure

When an enum mapping does not contain all possible enums, users can get cryptic errors when calling ->toOne().  This change aims to provide the user with a more meaningful error message that should help them self-troubleshot.

Improve error message when enum value is not found on enum mapping

---

legend-pure-code-compiled-core/src/main/resources/core/java/metamodel_factories.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/mathLibrary.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/langLibraryTests.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/mathLibraryTests.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/testUtils.pure

This also cleans up "alloy only" test cases, which are not been executed on legend-engine in preparation to enable them.
Blocks: https://github.com/finos/legend-engine/pull/661

Add java conventions for pow and decimal divide functions

---

legend-pure-code-compiled-core/src/main/resources/core/java/metamodel_factories.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/langExtension.pure

Both branches in a Java conditional need to be of the same type: in the case that one branch is a primitive type, but the other branch is the equivalent boxed type this change boxes the primitive type so that both branches are consistent in their return value type.

Java factory: box primitive number branches to fix type inference

---

legend-pure-m2-dsl-mapping/src/main/resources/platform/pure/mapping.pure
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataLazy.java

When running our PURE compiled jar with multiple threads, we occasionally (at the start of the run) get errors like this:
"Cannot find enum 'A' in enumeration 'a::s::d::f' unknown enum value (known values: 'A','B','C','D')
Which implies that the enum is valid but couldn't be found.  Looking at the code behind this, it appears it's possible that there is an edge case where the enum is being populated at the same time as it's being looked up. (and the population code explicitly caters for this partially populated scenario).  Since this is a transient error I'm going to try applying this fix to my local codebase to see if it actually fixes the error - but in the meantime any thoughts would be greatly appreciated.
- monica

Attempt to fix error with partially loaded enum metadata

---

legend-pure-maven-compilation-par/pom.xml
legend-pure-maven-compilation-par/src/main/java/org/finos/legend/pure/maven/par/PureJarMojo.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataLazy.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/binary/DistributedBinaryGraphDeserializer.java

Currently, PureJaraMojo requires extra repositories to be specified as file paths. This allows it alternately to be specified as resource names.

Allow extraRepositories to be resource names in PureJarMojo

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/repository/CodeRepository.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/filesystem/repository/TestCodeRepository.java

Handle an edge case in repository sorting. Specifically, handle the case of different repositories with the same name. This is a highly unusual but theoretically possible case.

Handle an edge case in repository sorting

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/inlinedsl/InlineDSL.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/AbstractCompiledStateIntegrityTest.java
legend-pure-m3-dsl-graph/src/main/java/org/finos/legend/pure/m3/inlinedsl/graph/antlr/GraphDSL.java
legend-pure-m3-dsl-path/src/main/java/org/finos/legend/pure/m3/inlinedsl/path/NavigationPath.java
legend-pure-m3-dsl-path/src/main/java/org/finos/legend/pure/m3/inlinedsl/path/parser/NavigationGraphBuilder.java
legend-pure-m3-dsl-path/src/main/java/org/finos/legend/pure/m3/inlinedsl/path/parser/NavigationParser.java
legend-pure-m3-dsl-path/src/main/java/org/finos/legend/pure/m3/inlinedsl/path/processor/PathProcessor.java
legend-pure-m3-dsl-path/src/main/java/org/finos/legend/pure/m3/inlinedsl/path/unloader/PathUnbind.java
legend-pure-m3-dsl-path/src/main/java/org/finos/legend/pure/m3/inlinedsl/path/validation/PathValidator.java
legend-pure-m3-dsl-path/src/main/java/org/finos/legend/pure/m3/inlinedsl/path/walker/PathWalk.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/IdBuilder.java

Stabilize compiled mode metadata ids for Path instances. In passing, clean up some of the code in the Path DSL.

Stabilize compiled mode metadata ids for Path instances

---

legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/json/AbstractTestFromJson.java
legend-pure-runtime-java-extension-external-json/src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonAnyTypeDeserialization.java
legend-pure-runtime-java-extension-external-json/src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonDeserializationCache.java
legend-pure-runtime-java-extension-external-json/src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonSerializationCache.java
legend-pure-runtime-java-extension-external-shared/src/main/java/org/finos/legend/pure/runtime/java/extension/external/shared/conversion/ConversionCache.java

This will allow to parse json values into properties of type Any.  This will only work for values that are primitive types (integer, float, string, boolean)
The rational - Im currently trying to parse the Elastic Search specification json, and one of their types (literal_value) have a property that can be any primitive type, and without this enhancement, I not able to get the proper value.
Sample json from ES spec:
```json
[ {
"name": "model",
"required": true,
"type": {
"kind": "literal_value",
"value": "linear"
}
},
{
"name": "managed",
"required": true,
"type": {
"kind": "literal_value",
"value": true
}
}]
```
The `type` field are mapped into this Pure Type, where value is Any to be able to contain Boolean and String:
```legend
Class …
```

Support Any properties for primitive values on fromJson

---

legend-pure-ide-light/pom.xml
legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/PureIDEServer.java

This will allow developers to just configure the repos they need to actually edit, and the others are sourced from classpath.
This can be useful when working on 3rd party projects, where the focus its to edit the local files, and the pure dependencies can be read only.  On this same scenario, this can avoid needing to checkout the legend-pure and legend-engine to make the IDE work.

Support loading code repos from classpath when configuring IDE light

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/bootstrap/generator/M3CoreInstanceGenerator.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/coreinstance/helper/PropertyTypeHelper.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/ClassJsonFactoryProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassProcessor.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/TestClassWithParamSuperType.java

This ensure we generate proper java code when a property contains type arguments, and these type arguments are then defined on a subclass of it.

Handle properties with type parameters defined on supertype

---

legend-pure-m2-dsl-mapping/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/processor/AggregationAwareProcessor.java
legend-pure-m2-dsl-mapping/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/processor/PureInstanceSetImplementationProcessor.java
legend-pure-m2-dsl-mapping/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/processor/XStoreProcessor.java
legend-pure-m2-dsl-mapping/src/test/java/org/finos/legend/pure/m2/ds/mapping/test/TestXStoreMapping.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/PostProcessor.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/ProcessorState.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/inference/PrintTypeInferenceObserver.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/inference/TestTypeInferenceObserver.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/inference/TypeInference.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/observer/CombinedPostProcessorObserver.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/observer/FilterPostProcessorObserver.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/observer/NetTimingPostProcessorObserver.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/observer/PostProcessorObserver.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/observer/SimpleTimingPostProcessorObserver.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/observer/TimingPostProcessorObserver.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/observer/TracingPostProcessorObserver.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/observer/VoidPostProcessorObserver.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/UnitProcessor.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/inlinedsl/treepath/RootRouteNodePostProcessor.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/IncrementalCompiler.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/IncrementalCompiler_New.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/IncrementalCompiler_Old.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/PureRuntime.java

Add post-processing observers, that can allow better information about what post-processing is doing. For example, this can allow timing of instance processing or tracing of how instances are processed.
Also, improve variable context handling so that it can be done with try-with-resources. This should ensure that whenever a new context is pushed, it is always popped.

Add post-processing observers and improve variable context handling

---

legend-pure-configuration-external/pom.xml
legend-pure-configuration-external/src/main/java/org/finos/legend/pure/configuration/PureRepositoriesExternal.java
legend-pure-configuration-external/src/test/java/org/finos/legend/pure/configuration/TestPureRepositoriesExternal.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/repository/CodeRepositoryProviderHelper.java

Index repositories by name in a thread local to avoid conflicts where compilation steps in concurrent threads are clearing and recomputing the sets of available repositories.

Index repositories by name in a thread local to avoid thread conflicts

---

legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/modeling/function/TestFunctionEval.java

Add a ToFix test for a Java generation bug where the system is generating a Java non-statement for Pure code calling the eval function and ignoring its return value.

Add a ToFix test for a Java generation bug

---

legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/constraints/AbstractTestConstraintsHandler.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Pure.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/valuespecification/ValueSpecificationProcessor.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/modeling/function/TestLambdasWithTypeParameters.java

Fix a Java generation bug with a lambda with a not fully concrete return type. Specifically, the issue occurred when the return type was concrete at the top level but had nested type or multiplicity parameters.

Fix a Java generation bug with lambdas with non-concrete return types

---

legend-pure-maven-java-compiled/pom.xml
pom.xml

Update dependency versions to fix security vulnerabilities with commons-text ([CVE-2022-42889](https://www.mend.io/vulnerability-database/CVE-2022-42889)), maven-shared-utils ([CVE-2022-29599](https://www.mend.io/vulnerability-database/CVE-2022-29599)), and snakeyaml ([CVE-2022-38750](https://www.mend.io/vulnerability-database/CVE-2022-38750), [CVE-2022-38751](https://www.mend.io/vulnerability-database/CVE-2022-38751), [CVE-2022-38752](https://www.mend.io/vulnerability-database/CVE-2022-38752), [CVE-2022-38749](https://www.mend.io/vulnerability-database/CVE-2022-38749), [CVE-2022-25857](https://www.mend.io/vulnerability-database/CVE-2022-25857)).

Update dependency versions to fix security vulnerabilities

---

legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/AbstractTestFunctionDefinitionModify.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaSourceCodeGenerator.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Bridge.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CoreExtensionCompiled.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/DynamicPureFunctionImpl.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/LambdaCompiledExtended.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Pure.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Reactivator.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/measureUnit/UnitImplProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/valuespecification/ValueSpecificationProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/JavaMethodWithParamsSharedPureFunction.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/TestFunctionDefinitionModify.java
legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/core/lang/Copy.java
legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/TestFunctionDefinitionModify.java

Previously modifying the expression sequence and then invoking eval caused the (original pre-compiled) pureFunction, with logic corresponding to the original expression sequence, to executed giving incorrect / unexpected results.
Primary change is to make PureCompiledLambda immutable.  It is essentially a wrapper around a LambdaFunction that pairs it with a pre-compiled / generated implementation of SharedPureFunction.  This change modifies this wrapper class so that on any modifications it unwraps / returns the LambdaFunction, which will then be routed to DynamicPureFunctionImpl to be handled dynamically.

Update for compiled mode so that evaluation of lambdas where the expressionSequence has modified is in sync / matches

---

legend-pure-configuration-external/src/main/java/org/finos/legend/pure/configuration/PureRepositoriesExternal.java
legend-pure-ide-light/pom.xml
legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/PureIDEServer.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/repository/CodeRepositoryProviderHelper.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/repository/CodeRepositorySet.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/repository/GenericCodeRepository.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/filesystem/repository/TestCodeRepositorySet.java
legend-pure-maven-compilation-par/pom.xml
legend-pure-maven-compilation-par/src/main/java/org/finos/legend/pure/maven/par/PureJarMojo.java
legend-pure-maven-compilation-par/src/main/java/org/finos/legend/pure/maven/par/PureJarSerializer.java
legend-pure-maven-java-compiled/pom.xml
legend-pure-maven-java-compiled/src/main/java/org/finos/legend/pure/maven/javaCompiled/PureCompiledJarMojo.java

Since repositories are found through the Java service loader framework, a static cache of them makes little sense. This deprecates that static cache (PureRepositoriesExternal) and replaces it with a non-static class (CodeRepositorySet) which guarantees the same integrity, but is more flexible and eliminates concurrency issues.

Replace PureRepositoriesExternal with CodeRepositorySet

---

legend-pure-code-compiled-tests/src/main/java/org/finos/legend/pure/code/core/compiled/test/IgnoreUnsupportedApiPureTestSuiteRunner.java

We need a way to indicate unsupported-api, when implementing extension apis. When extension api tests are run, if tests throw unsupported-api exception, then such tests should be treated as ignored by junit.

Introduce IgnoreUnsupportedApiPureTestSuiteRunner

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/ElementWithConstraintsProcessor.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/valuespecification/FunctionExpressionProcessor.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/validation/validator/ElementWithConstraintsValidator.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/validation/validator/PackageableFunctionValidator.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/multiplicity/Multiplicity.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/constraints/AbstractTestConstraints.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/literal/TestInstanceCollectionType.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/literal/TestLiteral.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/literal/TestMultiplicity.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/literal/TestNestedCollection.java

Validate function definitions and message functions in constraints. These were previously not being validated.
Validating these has revealed issues with parsing and post-processing of constraints. In particular, type and multiplicity parameters from the owning class (if present) were not being included in the type of the parameter "this". These issues are also fixed.

Validate function definitions and message functions in constraints

---

legend-pure-m2-functions-pure/src/main/resources/platform_functions/date/today.pure
legend-pure-m2-functions-pure/src/main/resources/platform_functions/runtime/currentUserId.pure
legend-pure-m3-core/src/main/antlr4/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/core/M3CoreParser.g4
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/lang/all.pure
legend-pure-m3-core/src/main/resources/platform/pure/grammar/milestoning.pure
legend-pure-m3-core/src/main/resources/platform/pure/profile.pure
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/TestClassLoaderCodeStorage.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/grammar/v1/TestM3AntlrParser.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/modeling/function/TestFunctionReturnMultiplicity.java

This PR introduces `functionType` profile with `SideEffect` stereotype which would be used to mark `SideEffect` functions whose executions are impacted by external factors.
Ex - I/O functions (like getAll), today

Introduce functionType profile

---

legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataLazy.java

This PR changes the behavior of `MetadataLazy` to align with the behavior of `MetadataEager`. 
While fetching metadata of non-existing classifiers an empty map should be returned instead of null to avoid NPE down the stack.

Return empty map when fetching metadata for non-existing classifier

---

legend-pure-ide-light/pom.xml
legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/api/FileManagement.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/PureCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/CodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/MutableCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/Source.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/runtime/TestSourceNavigation.java

Refer to https://github.com/finos/legend-studio/pull/1822 and https://github.com/finos/legend-studio/pull/1877 for the full changelog

Pure IDE: more improvements

---

legend-pure-m2-store-relational-pure/src/main/resources/platform_store_relational/functions.pure
legend-pure-m2-store-relational-pure/src/main/resources/platform_store_relational/grammar/relational.pure

To have query metadata for every execution we are prepending SQL Queries with SQL Comments to hold the execution trace ID (introduced as part of an associated change in Engine for this) which can be used to pull the respective zipkin trace.

Add Comments to SQLQuery metamodel

---

legend-pure-m2-store-relational-pure/src/main/resources/platform_store_relational/functions.pure
legend-pure-m2-store-relational-pure/src/main/resources/platform_store_relational/grammar/relational.pure

Reverting for now as it is blocking visibility on TeamCity, will merge with other backwards incompatible changes when starting with release.

Revert "Add Comments to SQLQuery metamodel (#656)"

---

legend-pure-m3-core/src/main/resources/platform/pure/profile.pure
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/modeling/function/TestFunctionReturnMultiplicity.java

Add a new stereotype to mark functions as requiring a preeval/normalize call before being routed.

Function stereotype to signify normalize/preeval required

---

legend-pure-runtime-java-extension-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/shared/connectionManager/TestDatabaseConnect.java

Adds missing new keywords (when compared to v1.4.200) to preserve compatibility through upgrade.
Deletes duplicate 'TO'.

Add more non_keywords for compatibility

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/property/AbstractTestDefaultValue.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/property/TestDefaultValue.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/property/TestProperty.java
legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/TestDefaultValueInterpreted.java

Fix lambda ids for property default values. The previous id scheme did not yield unique ids.

Fix lambda ids for property default values

---

legend-pure-runtime-java-extension-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/interpreted/natives/ExecuteInDb.java
legend-pure-runtime-java-extension-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/shared/connectionManager/TestDatabaseConnect.java

Required to handle new parsedatetime() return values in interpreted mode and to better match previous H2's SQL semantics.
More detail on compatibility can be found: https://www.h2database.com/html/features.html#compatibility

Add more H2 backward compatibility settings

---

legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/api/FileManagement.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/RepositoryRevisionCache.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/PureModelVersion.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/VersionControlledClassLoaderCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/composite/CompositeCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/vcs/Revision.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/vcs/VersionControlledCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/binary/BinaryModelRepositorySerializer.java

Switch VCS revisions to String from Long to enable work on Git Code Storage

Switch VCS revisions to String from Long

---

legend-pure-m2-store-relational-pure/src/main/resources/platform_store_relational/relationalRuntime.pure

SingleStore Managed services will reuse MemSQL DatabaseType

Remove DB type SingleStore to reuse MemSQL

---

legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/meta/AbstractTestInstanceOf.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/basics/meta/InstanceOf.java

Resolves issues with pre-eval 
```
Caused by: java.lang.UnsupportedOperationException: Not Implemented for function: instanceOf_Any_1__Type_1__Boolean_1_
at org.finos.legend.pure.generated.platform_pure_basics_meta_instanceOf$1.execute(platform_pure_basics_meta_instanceOf.java:33)
at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.Pure._evaluateToMany(Pure.java:429)
at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.Reactivator.reactivateWithoutJavaCompilationImpl(Reactivator.java:282)
at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.Reactivator.reactivateWithoutJavaCompilationImpl(Reactivator.java:169)
at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.Reactivator.reactivateWithoutJav …
```

Fix & test for instanceOf being used in a re-activate/compile value specification flow

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/vcs/MutableVersionControlledCodeStorage.java

Add update functions to MutableVCS interface to use string functions.
Default functions added and existing functions marked as deprecated to make interface change backwards compatible.

Modify Mutable VCS interface to support string revision references

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/PureModelVersion.java

Deleting legacy code - we should use the non-JSON method and let client handle formatting if need. Current usages take the JSON and parse to get the model version number - so we may as well just use the non-JSON method and get version number directly

Remove static JSON method in PureModelVersion

---

legend-pure-maven-generation-java/src/main/java/org/finos/legend/pure/maven/javaCompiled/PureCompiledJarMojo.java
legend-pure-maven-generation-par/src/main/java/org/finos/legend/pure/maven/par/PureJarMojo.java

Avoid warning when executing maven with multithreading option

Avoid warning when executing maven with multithreading option

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/SourceInformation.java
legend-pure-m4/src/test/java/org/finos/legend/pure/m4/coreinstance/TestSourceInformation.java

Add SourceInformation.subsumes. This is similar to the existing contains method, but it takes the source id into account. The contains method is deprecated and kept only for backward compatibility.

Add SourceInformation.subsumes

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/pattern/URLPatternLibrary.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/runtime/pattern/TestURLPatternLibraryOrder.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/validation/TestServiceURL.java

Fix URLPatternLibrary regex exception handling, specifically the generation of the source information. Previously the end coordinates were not supplied. Also, the previous behavior yielded different results depending on the Java version in use. This, in particular, meant that the success of some tests depended on the Java version.
In passing, use named groups in the main regex to make the code clearer.

Fix URLPatternLibrary regex exception handling

---

.github/workflows/build.yml
.github/workflows/clean-after-failed-release.yml
.github/workflows/legend-stack-release.yml
.github/workflows/ossrh-close-staging-repo.yml
.github/workflows/release.yml
legend-pure-m3-core/pom.xml
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/ParserLibrary.java
legend-pure-runtime-java-engine-compiled/pom.xml
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/compiler/PureJavaCompiler.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaSourceCodeGenerator.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/ClassJsonFactoryProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/NativeFunctionProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassImplProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassLazyImplProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/measureUnit/MeasureImplProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/measureUnit/MeasureInterfaceProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/measureUnit/UnitImplProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/measureUnit/UnitInstanceImplProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/measureUnit/UnitInstanceInterfaceProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/measureUnit/UnitInterfaceProcessor.java
legend-pure-runtime-java-extension-dsl-graph/pom.xml
legend-pure-runtime-java-extension-dsl-path/pom.xml
legend-pure-runtime-java-extension-functions-json/pom.xml
legend-pure-runtime-java-extension-functions-relation/pom.xml
legend-pure-runtime-java-extension-functions/pom.xml
legend-pure-runtime-java-extension-store-relational/pom.xml
pom.xml

Support building and running with Java 17. The system remains compatible with both Java 8 and 11.
Upgrade the project workflows to use Java 17 instead of 11.
Note that because dynamic compilation of generated Java code is done with source and target Java 7, the system remains incompatible with Java 20 and later (as support for source/target/release 7 was dropped in Java 20).

Support building and running with Java 17

---

legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/collection/map.pure
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/grammar/collection/Map.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Reactivator.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/modeling/function/TestFunctionReturnMultiplicity.java

Fix a bug with the implementation of map in compiled mode.  Specifically, the implementation used when calling map via eval/evaluate didn't properly handle the case where the collection to map over had cardinality 1 or 0..1.
In passing, add better error handling in Reactivator.

Fix a bug with the implementation of map in compiled mode

---

legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/boolean/conjunctions/and.pure
legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/boolean/conjunctions/or.pure
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/_boolean/AbstractTestAnd.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/_boolean/AbstractTestNot.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/_boolean/AbstractTestOr.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/basics/lang/If.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Reactivator.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/modeling/function/TestFunctionReturnMultiplicity.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/_boolean/TestCompileAnd.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/_boolean/TestCompileNot.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/_boolean/TestCompileOr.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/_boolean/TestCompilePrecedence.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/lang/TestIfCompiled.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/_boolean/TestInterpretedAnd.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/_boolean/TestInterpretedNot.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/_boolean/TestInterpretedOr.java

Fix bug with dynamic evaluation of and/or to ensure that both are short-circuit operations. That is, conjuncts/disjuncts are evaluated in order and evaluation is terminated once one evaluates to false/true. This is particularly important for cases where later conjuncts/disjuncts depend on previous ones, such as instanceOf checks followed by casts.

Fix bug with dynamic evaluation of and/or

---

.github/workflows/build.yml
.github/workflows/legend-stack-release.yml
.github/workflows/ossrh-close-staging-repo.yml
.github/workflows/release.yml

Upgrade workflow action versions:
- actions/cache to v4
- actions/setup-java to v4
- actions/setup-node to v4
- actions/upload-artifact to v4

Upgrade workflow action versions

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/inference/TypeInferenceContext.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/valuespecification/FunctionExpressionProcessor.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/validation/validator/FunctionExpressionValidator.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/M3PropertyPaths.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/function/FunctionType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/GenericType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/Support.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/match/TypeMatch.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_Column.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_RelationType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/type/Type.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/inference/TestFunctionTypeInference.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/FunctionExpressionExecutor.java

Fix a bug with contravariant type inference with non-concrete generic types. This can occur with function expressions that return function types where one of the parameter types might be non-concrete. For example, consider this function:
```
function collectionToStrings<T|m>(col:T[m], func:Function<{T[1]->String[1]}>[0..1]):String[m]
{
let toStringFunc = if($func->isEmpty(), |{x:T[1] | $x->toString()}, |$func->toOne());
$col->map(x | $toStringFunc->eval($x));
}
```
The issue would occur in computing the type for the if expression. Before the fix, the type would be computed as `Function<Nil[1]->String[1]>`, whereas it should be `Function<T[1]->String[1]>`.
This also improves how generic types are hashed when finding the best common generic type. The previous hashing strategy was not fully …

Fix contravariant type inference with type parameters

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/basics/meta/elementToPath.pure
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/basics/meta/ElementToPath.java

Fix  a bug in the interpreted mode implementation of elementToPath with ephemeral PackageableElements. These are PackageableElements that are created at runtime, rather than compile time, and are anonymous with respect to the compiled graph. They may or may not have values for the name property.
Tests are added for such cases.

Fix interpreted mode implementation of elementToPath

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/basics/meta/elementToPath.pure
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/_enum/AbstractTestEnumeration.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/_enum/TestEnumerationValues.java
legend-pure-functions/legend-pure-functions-base/legend-pure-m2-functions-base-pure/src/main/resources/platform_functions/meta/newAssociation.pure
legend-pure-functions/legend-pure-functions-base/legend-pure-m2-functions-base-pure/src/main/resources/platform_functions/meta/newClass.pure
legend-pure-functions/legend-pure-functions-base/legend-pure-m2-functions-base-pure/src/main/resources/platform_functions/meta/newEnumeration.pure
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/meta/NewEnumeration.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/natives/meta/NewAssociation.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Pure.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/modeling/_enum/TestEnumeration.java

Add tests for ephemeral PackageableElements, primarily for elementPath and elementToPath. Add tests specifically for ephemeral elements created by newClass, newEnumeration, and newAssociation.
Also, fix an issue with the compiled mode implementation of newEnumeration, and improve the compiled mode implementation for creating ephemeral packages when they do not exist.

Add tests for ephemeral PackageableElements

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/Support.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/inference/TestFunctionTypeInference.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/inference/TestReturnInference.java

Fix handling of type parameters when computing best generic type. In particular, this extends a fix from one special case (covariant with 1 concrete generic type) to all cases (covariant and contravariant with any number of concrete generic types).

Fix handling of type parameters when computing best generic type

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/inference/TestFunctionTypeInference.java

Add more tests for type inference for if expressions. Also, group the if type inference tests in TestFunctionTypeInference together.

Add more tests for type inference for if expressions

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/_class/AbstractTestConstraints.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/io/AbstractTestHttp.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/io/AbstractTestPrint.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/io/AbstractTestReadFile.java
legend-pure-core/legend-pure-m3-core/src/test/resources/read_file_test/io/readFileTestText.txt
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsHelper.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/io/ReadFile.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/io/TestHttpCompiled.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/io/TestPrintCompiled.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/io/TestReadFile.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/FunctionExtensionInterpreted.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/natives/io/ReadFile.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/io/TestPrint.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/io/TestReadFile.java

Add an optional lineSeparator parameter to readFile native function. When supplied, line separators in the underlying text will be replaced with the give line separtor. This can be used, for example, to ensure line separator consistency independently of the underlying file system.

Add optional lineSeparator parameter to readFile native function

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/GraphPath.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/navigation/graph/TestGraphPath.java

Graph path fixes and improvements.
Fix parsing bugs where invalid graph path descriptions were being parsed without error. Add tests to make sure invalid strings yield errors in parsing.
Also, make the various concrete edge classes public, and add a visitor interface for them.

Graph path fixes and improvements

---

legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/SourceInformation.java
legend-pure-core/legend-pure-m4/src/test/java/org/finos/legend/pure/m4/coreinstance/TestSourceInformation.java

Fix a bug in SourceInformation.isValid that failed to catch some cases where the main or end column was invalid. Add corresponding tests.

Fix a bug in SourceInformation.isValid

---

legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CompiledSupport.java

Make CompiledSupport.makeOne more strict, so that it throws an exception if there is more than one value.

Make CompiledSupport.makeOne more strict

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/m3.pure
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/lineinfo/TestLineInfo.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/orchestrator/JavaCodeGeneration.java

Define packages individually in m3.pure. Add a test to ensure we have the correct core packages in the correct hierarchy.
In passing, remove some unnecessary exception wrapping in JavaCodeGeneration.

Define packages individually in m3.pure

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/m3.pure
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/_class/TestClass.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/_class/TestClassWithConstraints.java

Fix a bug in Constraint parsing where strings were not properly unescaped. Add tests for this and some other Constraint parsing/compilation cases.
Make Constraint extend ModelElement instead of PackageableElement, since constraints are never in the package tree.

Fix contraint model and parsing

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/TestM3CoreCompiledStateIntegrity.java
legend-pure-dsl/legend-pure-dsl-diagram/legend-pure-m2-dsl-diagram-pure/pom.xml
legend-pure-dsl/legend-pure-dsl-diagram/legend-pure-m2-dsl-diagram-pure/src/test/java/org/finos/legend/pure/m2/dsl/diagram/TestM2DiagramCompiledStateIntegrity.java
legend-pure-dsl/legend-pure-dsl-graph/legend-pure-m2-dsl-graph-pure/pom.xml
legend-pure-dsl/legend-pure-dsl-graph/legend-pure-m2-dsl-graph-pure/src/test/java/org/finos/legend/pure/m2/inlinedsl/graph/TestM2GraphCompiledStateIntegrity.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-pure/pom.xml
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-pure/src/test/java/org/finos/legend/pure/m2/dsl/mapping/TestM2MappingCompiledStateIntegrity.java
legend-pure-dsl/legend-pure-dsl-path/legend-pure-m2-dsl-path-pure/pom.xml
legend-pure-dsl/legend-pure-dsl-path/legend-pure-m2-dsl-path-pure/src/test/java/org/finos/legend/pure/m2/inlinedsl/path/TestM2PathCompiledStateIntegrity.java
legend-pure-dsl/legend-pure-dsl-store/legend-pure-m2-dsl-store-pure/pom.xml
legend-pure-dsl/legend-pure-dsl-store/legend-pure-m2-dsl-store-pure/src/test/java/org/finos/legend/pure/m2/dsl/store/TestM2StoreCompiledStateIntegrity.java
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-pure/pom.xml
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-pure/src/test/java/org/finos/legend/pure/m2/inlinedsl/tds/TestM2TDSCompiledStateIntegrity.java
legend-pure-functions/legend-pure-functions-base/legend-pure-m2-functions-base-pure/pom.xml
legend-pure-functions/legend-pure-functions-base/legend-pure-m2-functions-base-pure/src/test/java/org/finos/legend/pure/m2/functions/TestM2FunctionsBaseCompiledStateIntegrity.java
legend-pure-functions/legend-pure-functions-json/legend-pure-m2-functions-json-pure/pom.xml
legend-pure-functions/legend-pure-functions-json/legend-pure-m2-functions-json-pure/src/test/java/org/finos/legend/pure/m2/functions/json/TestM2FunctionsJsonCompiledStateIntegrity.java

Add an easier initialize method to AbstractCompiledStateIntegrityTest. Add compiled state integrity tests for all DSLs and base and json functions.

Improve compiled state integrity tests

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/_package/_Package.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractImportGroupsTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/TestImportGroups_Pure.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/incremental/profile/TestPureRuntimeStereotype.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/incremental/projection/TestPureRuntimeProjection.java
legend-pure-dsl/legend-pure-dsl-diagram/legend-pure-m2-dsl-diagram-grammar/src/test/java/org/finos/legend/pure/m2/dsl/diagram/TestImportGroups_Diagram.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/MappingParser.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/test/java/org/finos/legend/pure/m2/dsl/mapping/TestImportGroups_Mapping.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/incremental/profile/TestPureRuntimeStereotypeCompiled.java

Fix an issue where duplicate import groups were being created under certain circumstances. This was happening in cases where a DSL (such as Mapping or Diagram) parsed a code section, transformed it into M3 grammar, and then sent that to the M3 parser. In cases like that, both the DSL parser and the M3 parser would create an import group for the same section. Now the M3 parser only creates an import group if it cannot find one that already exists for the section.
Add tests to ensure there are no duplicate import groups and that import groups had the expected imports.

Fix duplicate import groups

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/SourceInformation.java
legend-pure-core/legend-pure-m4/src/test/java/org/finos/legend/pure/m4/coreinstance/TestSourceInformation.java

Source information with 0 for a line or column value occurs with ImportGroups with no Imports. In the case of an import group for the initial implicit Pure section of a file with no imports, all line and column values will be 0. In the case of an import group for an explicit section with no imports, all column values will be 0 and line values will be the line of the section declaration (e.g., ###Mapping).
To accommodate this, we allow SourceInformation for these two cases to be valid. These can be characterized as cases where all column values are 0 and all line values are equal and non-negative. Otherwise, validity still requires line and column values to be strictly positive.
Additionally, we have updated our compiled state integrity test to ensure that all PackageableElements, …

Import group source information validity

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/generator/par/PureJarGenerator.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/repository/CodeRepositorySet.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/filesystem/repository/TestCodeRepositorySet.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractImportGroupsTest.java

Add subset method for CodeRepositorySet.Builder. This allows building a subset out of a larger set that may not be completely well defined. For example, this could allow building a well defined subset out of a larger set where some dependencies not involved in the subset are missing.
Also, do not automatically add platform repository either to subsets or the builder in general.

Add subset method for CodeRepositorySet.Builder

---

legend-pure-core/legend-pure-m3-bootstrap-generator/src/main/java/org/finos/legend/pure/m3/bootstrap/generator/M3ToJavaGenerator.java
legend-pure-core/legend-pure-m3-core/src/main/antlr4/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/core/M3CoreParser.g4
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/exception/PureUnresolvedIdentifierException.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/generator/bootstrap/M3CoreInstanceGenerator.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/M3PropertyPaths.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/function/FunctionType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_RelationType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/type/Type.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/binary/reference/StereotypeReferenceSerializer.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractTestMeasure.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaPackageAndImportBuilder.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/EnumProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/TypeProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/TestJavaPackageAndImportBuilder.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/TestTypeProcessor.java

Assorted fixes and code clean-up:
- clean up parsing for enums, measures, and units
- clean up PureUnresolvedIdentifierException
- clean up Java class/interface name generation
- fix wrapping handling in some type checks
- fix a minor issue in StereotypeReferenceSerializer

Assorted fixes and code clean-up

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/essential/lang/unit/newUnit.pure
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractTestMeasure.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/essentials/lang/unit/NewUnit.java

Fix a bug in the compiled mode Java generation for newUnit. It was failing in case the unit was not concretely specified (e.g., it was coming from a variable or function expression). Tests are added for such cases.

Fix a bug in the compiled mode Java generation for newUnit

---

legend-pure-core/legend-pure-m3-core/src/main/antlr4/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/core/M3CoreParser.g4
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/essential/lang/creation/dynamicNew.pure
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/AbstractCompiledCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/DefaultValue.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/resources/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/core/CoreGen.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/essentials/lang/creation/DynamicNew.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/grammar/lang/creation/New.java

Fixes and improvements for default values in dynamicNew:
- in compiled mode, default values are now computed lazily and only when needed
- in compiled mode, default values for inherited properties are now handled
- in interpreted mode, the native implementation of dynamicNew now handles non-constant default values
- tests for dynamicNew with non-constant default values
- tests for dynamicNew with inherited properties with default values
- fix the parser for default values to allow negative numbers

Fixes and improvements for default values in dynamicNew

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/ConcreteFunctionDefinitionNameProcessor.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/function/FunctionDescriptor.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/GraphPath.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/navigation/graph/TestGraphPath.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/TestFunction.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/TestFunctionDescriptor.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/tools/TextTools.java
legend-pure-core/legend-pure-m4/src/test/java/org/finos/legend/pure/m4/tools/TestTextTools.java

Fix names for functions with units in the signature. Previously, they could be invalid identifiers. Add a test to ensure all elements in the package tree have valid identifiers as names.

Fix names for functions with units in the signature

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/ParserLibrary.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/top/TopGraphBuilder.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/SourceRegistry.java

Fix the exception message in TopGraphBuilder for when a parser required by the code is missing. In passing, add some missing type parameters.

Fix missing parser exception message in TopGraphBuilder

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/ParserLibrary.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/BinarySourceSerializer.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/GraphLoader.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/PureRuntime.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/binary/PureRepositoryJars.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/antlr/AggregationAwareGraphBuilder.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/antlr/MappingGraphBuilder.java

Initialize compiled state integrity tests from caches when possible. In passing, add a specific exception to ParserLibrary for unknown parsers.

Initialize compiled state integrity tests from caches when possible

---

legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/AbstractTestPureDBFunction.java
legend-pure-store/legend-pure-store-relational/legend-pure-runtime-java-extension-compiled-store-relational/pom.xml
legend-pure-store/legend-pure-store-relational/legend-pure-runtime-java-extension-compiled-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/compiled/natives/ResultSetValueHandlers.java
legend-pure-store/legend-pure-store-relational/legend-pure-runtime-java-extension-interpreted-store-relational/pom.xml
legend-pure-store/legend-pure-store-relational/legend-pure-runtime-java-extension-interpreted-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/interpreted/natives/ExecuteInDb.java
legend-pure-store/legend-pure-store-relational/legend-pure-runtime-java-extension-shared-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/shared/connectionManager/ConnectionManager.java
legend-pure-store/legend-pure-store-relational/legend-pure-runtime-java-extension-shared-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/shared/connectionManager/DuckDBConnectionWrapper.java
legend-pure-store/legend-pure-store-relational/legend-pure-runtime-java-extension-shared-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/shared/connectionManager/TestDatabaseConnect.java
legend-pure-store/legend-pure-store-relational/legend-pure-runtime-java-extension-shared-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/shared/connectionManager/TestDatabaseConnectDuckDB.java
pom.xml

- use dbtype in testdbconnection to switch between h2 and duckDB test connection in legend-pure connection manager
- use singleton connection for duckdb

add test connection execution for duck db in pure runtime

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/association/TestAssociation.java

Clean up Association tests. Add a test to verify that there is a compilation error when there is a property conflict coming from two different associations.

Clean up Association tests

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/validation/TestFunctionReturnType.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/grammar/antlr/AntlrSourceInformation.java

Fix source information for user defined primitive types and array expressions. In passing, clean up TestFunctionReturnType.

Source information fixes

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/exception/PureExecutionException.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/relation/TestRelationTypeInference.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassImplProcessor.java

Assorted minor fixes and clean-ups:
- improve error handling in PureExecutionException.printPureStackTrace
- fix a typo in AbstractCompiledStateIntegrityTest
- clean up TestRelationTypeInference
- clea up ClassImplProcessor

Assorted minor fixes and clean-ups

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/GraphPath.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/GraphPathIterable.java

Allow building and extending GraphPaths without validation. Skipping validation can yield performance improvements, but should only be done when the values in question are already known to be valid. The behavior of GraphPaths created with invalid values is undefined.

Allow building and extending GraphPaths without validation

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/runtime/binary/TestBinaryModelSourceSerializer.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/profile/TestProfile.java

Set the classifierGenericType for Profiles. In passing, abstract out the building and setting of packages in AntlrContextToM3CoreInstance.

Set classifierGenericType for Profiles

---

legend-pure-core/legend-pure-m3-bootstrap-generator/src/main/java/org/finos/legend/pure/m3/bootstrap/generator/M3ToJavaGenerator.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/relation/TestRelationTypeInference.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/pom.xml
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/antlr4/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/RelationMappingLexer.g4
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/antlr4/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/RelationMappingParser.g4
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/RelationMappingParser.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/antlr/RelationMappingGraphBuilder.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/processor/RelationFunctionInstanceSetImplementationProcessor.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/unloader/RelationFunctionInstanceSetImplementationUnbind.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/validator/RelationFunctionInstanceSetImplementationValidator.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.grammar.Parser
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/test/java/org/finos/legend/pure/m2/dsl/mapping/test/RelationMappingShared.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/test/java/org/finos/legend/pure/m2/dsl/mapping/test/TestRelationMapping.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/test/java/org/finos/legend/pure/m2/dsl/mapping/test/incremental/TestPureRuntimeRelationFunctionMapping.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-pure/src/main/java/org/finos/legend/pure/m2/dsl/mapping/M2MappingPaths.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-pure/src/main/java/org/finos/legend/pure/m2/dsl/mapping/M2MappingProperties.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-pure/src/main/resources/platform_dsl_mapping/grammar/mapping.pure
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/M2RelationalPaths.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/serialization/grammar/v1/RelationalParser.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/TestRelationAccessor.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/incremental/TestPureRuntimeClassMapping.java

Introduce new SetImplementation to support mapping functions relating Relations to Classes.

Support mapping Relations to Classes

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/CompiledStateIntegrityTestTools.java

Add compiled state integrity tests for annotation modelElement and function application source info

Add tests for annotation modelElement and function application source info

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/inference/PrintTypeInferenceObserver.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/inference/TestTypeInferenceObserver.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/inference/TypeInference.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/inference/TypeInferenceContext.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/_package/_Package.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/GenericType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/GenericTypeWithXArguments.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/GraphPathIterable.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/GraphStatistics.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/GraphTools.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/CompiledStateIntegrityTestTools.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/inference/TestFunctionTypeInference.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/tools/GraphWalkFilterResult.java

Fix an issue with resolved type parameters for function expressions where the generic type might have source information from an inappropriate location. In passing, improve some compiled state integrity failure messages, improve type inference observer output, and clean up some related code.

Fix an issue with resolved type parameters for function expressions

---

legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/processor/PropertyMappingProcessor.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/validator/PureInstanceSetImplementationValidator.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/test/java/org/finos/legend/pure/m2/dsl/mapping/test/TestModelMapping.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/test/java/org/finos/legend/pure/m2/dsl/mapping/test/TestXStoreMapping.java

Fix a bug in multiplicity for local mapping properties. Previously, the system was setting the property multiplicity to be 1, regardless of what was in the code.
In passing, fix an error message for multiplicity mismatch.

Fix a bug in multiplicity for local mapping properties

---

legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/test/java/org/finos/legend/pure/m2/dsl/mapping/test/TestModelMapping.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/serialization/grammar/v1/antlr/RelationalGraphBuilder.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/TestSimpleGrammar.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/TestXStoreMapping.java

Fix type parsing for local properties in Relational mappings. In passing, add a test for invalid types in local properties in Pure mappings.

Fix type parsing for Relational local mapping properties

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/relation/TestRelationTypeInference.java

Add tests(ignored) for Relation type inference issues. These tests are to reproduce the type inference issues faced for relation validation helper functions

Add tests(ignored) for Relation type inference issues

---

legend-pure-core/legend-pure-m3-precisePrimitives/pom.xml
legend-pure-core/legend-pure-m3-precisePrimitives/src/test/java/org/finos/legend/pure/code/core/TestPrecisePrimitivesCompiledStateIntegrity.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/DateFunctions.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/DateWithSubsecond.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataAccessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataHolder.java

Extend MetadataAccessor API with additional methods for getting different element types. In passing, add a compiled state integrity test for platform_precise_primitives and improve DateWithSubsecond.fromInstance.

Extend MetadataAccessor API

---

legend-pure-core/legend-pure-m3-core/pom.xml
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/InvalidReferenceIdException.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/ReferenceIdException.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/ReferenceIdExtension.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/ReferenceIdProvider.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/ReferenceIdProvisionException.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/ReferenceIdResolutionException.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/ReferenceIdResolver.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/ReferenceIds.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/UnresolvableReferenceIdException.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/ContainingElementIndex.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/ReferenceIdExtensionV1.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/ReferenceIdGenerator.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/ReferenceIdProviderV1.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/ReferenceIdResolverV1.java
legend-pure-core/legend-pure-m3-core/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.compiler.reference.ReferenceIdExtension
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/AbstractReferenceIdExtensionTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/AbstractReferenceTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/TestContainingElementIndex.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/TestReferenceIdExtensionV1.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/TestReferenceIdGenerator.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/test/java/org/finos/legend/pure/m2/dsl/mapping/serialization/compiler/reference/v1/TestReferenceIdExtensionV1Mapping.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/serialization/compiler/reference/v1/TestReferenceIdExtensionV1Relational.java

Add reference ids framework, including reference ids version 1. This provides unique and stable reference ids for all instances in the graph that have source information, excepting stubs and back references. The reference ids make use of graph paths and do not rely on any transient data, such as synthetic ids.

Add reference ids framework

---

legend-pure-core/legend-pure-m3-precisePrimitives/src/main/resources/platform_precise_primitives/precisePrimitives.pure
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/serialization/grammar/v1/RelationalParser.java

Remove potential conflictual names in precise primitives

Remove potential conflictual names in precise primitives

---

legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/testHelper/CodeCoverageGenerator.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/testHelper/FunctionExecutionInterpretedWithCodeCoverage.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/testHelper/PureTestBuilderInterpreted.java

This only works on interpreted mode.
The report track source information of the function calls, and then generate HTML displaying these.  When coverage overlaps, report generate darker green to display the nested function was called too.

Introduce code coverage track and report for Pure code

---

legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/tools/SafeAppendable.java

Fix SafeAppendable.append(CharSequence, int, int) for the implementing classes for StringBuilder and StringBuffer, which were not propertly propagating start and end parameters.

Fix SafeAppendable.append(CharSequence, int, int)

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/_class/AbstractTestDispatchQualifiedProperties.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/pct/features/TestDispatchQualifiedPropertiesCompiled.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/FunctionExecutionInterpreted.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/pct/features/TestDispatchQualifiedPropertiesInterpreted.java

Make dispatch work for qualified properties in Interpreted

Make dispatch work for qualified properties in Interpreted

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/_class/AbstractTestDispatchQualifiedProperties.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/lang/AbstractTestEvaluate.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/lang/TestEvaluate.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/FunctionExecutionInterpreted.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/lang/TestEvaluate.java

Fix qualified property dispatch for interpreted mode for three cases:
- when the qualified property is inherited but there is no override
- when the qualified property comes from an association
- when the instance comes from evaluateAndDeactivate
Tests are added for all three cases. Also, move tests for evaluate back from legend-engine.

Fix qualified property dispatch for interpreted mode

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/essential/collection/iteration/fold.pure
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/essentials/collection/iteration/Fold.java

Currently, the fold compile behavior expects its parameters to be VS Instance, and it leads to NPE when the parameters are VS VariableExpression.  This propose a change to generate proper java code when the parameter are variable expressions.

BugFix: Fix fold compile behavior to allow variable expressions on its parameters

---

legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/testHelper/PureTestBuilderCompiled.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/testHelper/PureTestBuilderInterpreted.java

The current tool to build test collection picks PCT test cases, while there are suites to execute PCT test cases already.  These leads to executing CPT test twice on each build cycle.

Enhancement: Skip pct test to avoid running these twice

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/coreinstance/KeyIndex.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/coreinstance/TestKeyIndex.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/AbstractQuantityCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/ReflectiveCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassLazyImplProcessor.java

Extract KeyIndex from ReflectiveCoreInstance so it can be used more generally. In passing, clean up generated imports in ClassLazyImplProcessor.

Extract KeyIndex from ReflectiveCoreInstance

---

legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/_boolean/TestCompileAnd.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/_boolean/TestCompileNot.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/_boolean/TestCompileOr.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/_boolean/TestCompilePrecedence.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/_boolean/TestInterpretedAnd.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/_boolean/TestInterpretedNot.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/_boolean/TestInterpretedOr.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/_boolean/TestInterpretedPrecedence.java

- Moving tests back to legend-pure from legend-engine, where their abstract classes are defined.
- Corresponding legend-engine PR for removal of these tests: https://github.com/finos/legend-engine/pull/3621

migrating function.base._boolean tests FROM engine TO pure

---

legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/GenericTypeSerializationInCode.java

Fix to rolling back using new reference ids in generated Java code. Add one missed change.

Fix to rolling back using new reference ids in generated Java code

---

pom.xml

- Improvement
We are replacing log4j-1.2.17 with reload4j-1.2.19 (This is done remove vulnerabilities). slf4j 1.7.36 version supports reload4j to keep in sync with other legend repo updating version over here as well.

Updates slf4j version to 1.7.36

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/exception/PureExecutionException.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/FunctionExpressionExecutor.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/DefaultConstraintHandler.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/runtime/api/TestFunctionExecutionStart.java

Fix execution exception callstacks for assertError. Previously, not everything was being popped off the stack in the case of errors that were caught.

Fix execution exception callstacks for assertError

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/runtime/AbstractTestCurrentUserId.java

Adding class back for build success, will work on moving this to legend-enginer.

Temporarily add back AbstractTestCurrentUserId

---

legend-pure-dsl/legend-pure-dsl-store/legend-pure-m2-dsl-store-pure/src/main/resources/platform_dsl_store/grammar/runtime.pure

Add preprocessFunction to Runtime to be able to rewrite a function expression before preval and routing if needed

Add preprocessFunction to Runtime

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/AbstractReferenceTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/TestReferenceIdGenerator.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java

Add reference id tests involving type variables. Also, add an integrity test for invalid classifiers and ensure that primitive types have classifierGenericType populated.

Add reference id tests involving type variables

---

legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaSourceCodeGenerator.java

Required to resolve issue in legend-engine with code generated to evaluate constraints on DynamicNew code
The modified code is covered by the existing unit test that generated code compiles.  The functional change needs to be tested in legend-engine (with a new test being added there)
`
java.lang.NullPointerException
at org.finos.legend.pure.runtime.java.compiled.generation.processors.IdBuilder.sourceToId(IdBuilder.java:376)
at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.CompiledSupport.executeFunction(CompiledSupport.java:1878)
at org.finos.legend.pure.runtime.java.compiled.generation.processors.support.Pure.handleValidation(Pure.java:715)
at org.finos.legend.pure.generated.core_pure_constraints_tests_constraintsExtension.Root_meta_pure_constraints_functions_ …

Default sourceInformation in PureCompiledLambda constructor to that of the provided LambdaFunction

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/_package/_Package.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/GraphPath.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/ReferenceIdExtension.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/ReferenceIds.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/ContainingElementIndex.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/ReferenceIdExtensionV1.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/ReferenceIdResolverV1.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/navigation/graph/TestGraphPath.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/AbstractReferenceIdExtensionTest.java

Generalize package path resolution for graph path and reference id resolution. Specifically, allow a general package path resolver to be passed in instead of a ProcessorSupport.

Generalize package path resolution for graph paths and reference ids

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/valuespecification/ValueSpecification.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/delta/CodeBlockDeltaCompiler.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/delta/MetadataEagerCompilerEventHandler.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/execution/CompiledExecutionSupport.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/execution/CompiledProcessorSupport.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/GenericTypeSerializationInCode.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaSourceCodeGenerator.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/ProcessorContext.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/IdBuilder.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/grammar/lang/all/GetAll.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/grammar/lang/creation/InstantiationHelpers.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CompiledSupport.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/AbstractLazyReflectiveCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/AbstractQuantityCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassLazyImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/measureUnit/MeasureProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/valuespecification/ValueSpecificationProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/Metadata.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataAccessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataBuilder.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataEager.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataLazy.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/GraphSerializer.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/runtime/CompiledMetadataStateVerifier.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/runtime/TestIdBuilder.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/runtime/serialization/TestGraphIsSerialized.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/runtime/serialization/TestLazyImplClassifiers.java

Use new reference ids in generated Java code. Change MetadataEager to lazily index by id to mitigate the effects of larger ids.

Use new reference ids in generated Java code

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/essential/meta/graph/pathToElement.pure

Add a test for using pathToElement to get a top level elements (Root, Package, String, Float, etc).

Add a test for using pathToElement to get a top level elements

---

legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-grammar/src/main/java/org/finos/legend/pure/m2/inlinedsl/tds/TDSExtension.java
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-runtime-java-extension-interpreted-dsl-tds/src/test/java/org/finos/legend/pure/runtime/java/extension/tds/interpeted/TestFunctionTester.java

Allow primitive types to be null. For int/long, using largest primes as unlikely we would see these on our test cases, rather than using min int/long, as these can be used for testing boundary conditions.

Support for nulls on primitives when parsing TDS

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/M3Paths.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/CoreHelper.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/valuespecification/FunctionExpressionProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/relation/TestColSpecType.java

In compiled mode the type of ColSpec was being set incorrectly as RelationType instead of setting the type as ColSpec with a type parameter that is of type RelationType

Fix bug when setting type of ColSpec in compiled mode

---

pom.xml

Move to default waitUntil config for central-maven-publishing

Move to default waitUntil config for central-maven-publishing

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/_class/_Class.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/AbstractCompiledCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/JavaCompiledCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/resources/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/core/CoreGen.java

Improve compiled mode generation for pureEquals and pureHashCode. In particular, sort the properties to ensure a deterministic order when there are multiple equality key properties.
Also, promote getDefaultValueKeys and getDefaultValue to JavaCompiledCoreInstance.

Improve compiled mode generation for pureEquals and pureHashCode

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/valuespecification/FunctionExpressionProcessor.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/GenericType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/pct/shared/PCTTools.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/inference/TestFunctionTypeInference.java
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-grammar/src/main/java/org/finos/legend/pure/m2/inlinedsl/tds/TDSExtension.java
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-runtime-java-extension-compiled-dsl-tds/src/main/java/org/finos/legend/pure/runtime/java/extension/dsl/tds/compiled/TDSNativeImplementation.java
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-runtime-java-extension-compiled-dsl-tds/src/main/java/org/finos/legend/pure/runtime/java/extension/dsl/tds/compiled/natives/StringToTDS.java
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-runtime-java-extension-interpreted-dsl-tds/src/main/java/org/finos/legend/pure/runtime/java/extension/dsl/tds/interpreted/natives/StringToTDS.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/CoreHelper.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/essentials/meta/type/relation/AddColumns.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/variant/AbstractTo.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/variant/FromJson.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/variant/ToVariant.java
legend-pure-runtime/legend-pure-runtime-java-engine-shared/src/main/java/org/finos/legend/pure/runtime/java/shared/variant/VariantInstanceImpl.java

These PR fixes and improve multiple miscellaneous areas:
- Improve type inference by recursively looking into Lambda return types.  For example, `V` will be inferred from the function parameter by recursively traverse the function return type:  `pkg::<V>testFunc(f: Function<{->List<Pair<String, V>>[1]}>[1]):Any[1]` 
- Ensure source information is assigned on RelationType instances, as its required for some visibility checks.
- Variant to use process support instance factory in shared code to ensure interpreted vs compile behavior is respected.  
- PCTTool - avoid index out of bounds when substring'ing.

Visibility check and inference fixes

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/essential/math/operation/mod.pure
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/essential/math/operation/rem.pure

These two functions can behave the same when both inputs are positive, but they differ when one is negative.  Adding some docs to help users understand the difference, as it could be intuitive to think `mod` is equivalent to `%` when in reality `rem` is the equivalent function.

Add rem and mod documentation

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/generator/bootstrap/M3CoreInstanceGenerator.java
legend-pure-maven/legend-pure-maven-generation-platform-java/pom.xml
legend-pure-maven/legend-pure-maven-generation-platform-java/src/main/java/org/finos/legend/pure/maven/platform/java/M3CoreInstanceGeneratorMojo.java
legend-pure-maven/pom.xml
pom.xml

Created mojo to generate java classes for pure platform.
Will be used in places where currently the exec-maven-plugin is being used to generate these classes.

Platform java generator mojo

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/GenericType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/valuespecification/ValueSpecification.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/execution/CompiledProcessorSupport.java

Update GenericType.print to work with simple core instances. As part of this, fix CompiledProcessorSupport.instance_instanceOf for subtypes of Number.

Update GenericType.print to work with simple core instances
