finos/legend-pure

legend-pure-ide-light/pom.xml
legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/PureIDEServer.java
legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/ServerConfiguration.java
legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/SourceLocationConfiguration.java
legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/session/PureSession.java

Make locations of Pure core source file configurable and allow option of keeping welcome.pure in persistent location in file system.
New configuration options are completely optional and not providing these configuration options will fallback to existing behaviour.

Pure IDE: add config for source file locations

---

legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/stringExtension.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/stringExtension.pure

Add two core String functions. isLetter() is to check if a string only consists of letters, isAlphaNumeric() is to check if string is alphaNumeric.

Add two core String functions.  isLetter() and isAlphaNumeric() 

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/validation/validator/ElementWithConstraintsValidator.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/validation/validator/FunctionDefinitionValidator.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/constraints/AbstractTestConstraints.java

This reverts commit 13e8cb628a6b3fc612ec68761e9a72fc3316aa36.

Revert "Check function expressions in constraints (#57)"

---

legend-pure-code-compiled-core/src/main/resources/core/pure/router/router_routing.pure

Add SQL generation support for isAlphaNumeric()

Exclude function isAlphaNumeric from routing

---

legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/common.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/mappingAdaptor.pure

Remove extra information added to exception (as part of : https://github.com/finos/legend-pure/pull/78) temporarily

Remove extra information added to exception temporarily

---

legend-pure-m3-core/src/main/antlr4/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/M3Lexer.g4
legend-pure-m3-core/src/main/antlr4/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/M3Parser.g4
legend-pure-m3-core/src/main/antlr4/org/finos/legend/pure/m3/serialization/grammar/treepathparser/TreePath.g4
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/M3Paths.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/M3AntlrParser.java
legend-pure-m3-core/src/main/resources/platform/pure/m3.pure
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/grammar/v1/TestStrictTimeParsing.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/lineinfo/TestLineInfo.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/validation/TestNewInstance.java
legend-pure-m4/src/main/antlr4/org/finos/legend/pure/m4/serialization/grammar/M4AntlrLexer.g4
legend-pure-m4/src/main/antlr4/org/finos/legend/pure/m4/serialization/grammar/M4AntlrParser.g4
legend-pure-m4/src/main/antlr4/org/finos/legend/pure/m4/serialization/grammar/M4Fragment.g4
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/ModelRepository.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/DateFormat.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/DateFunctions.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/StrictTime.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/StrictTimeWithMinute.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/StrictTimeWithSecond.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/StrictTimeWithSubsecond.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/grammar/M4GraphBuilder.java
legend-pure-m4/src/test/java/org/finos/legend/pure/m4/primitives/TestPureDate.java
legend-pure-m4/src/test/java/org/finos/legend/pure/m4/serialization/grammar/TestStrictTimeParsing.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/TestFunctionReturnMultiplicity.java

Support A New PURE Primitive Type: StrictTime

Support A New PURE Primitive Type: StrictTime

---

legend-pure-code-compiled-core/src/main/resources/core/java/metamodel_factories.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/alloyConventions.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/runtimeLibrary.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/runtimeLibraryTests.pure

Add support for generateGuid function in Java M2M code generation

Java gen: add support for generateGuid function

---

legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/testExplosion.pure

Replace Improper References in Tests.

Replace Improper References in Tests.

---

legend-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
legend-pure-code-compiled-core/src/main/resources/core/relational/SQLQueryToString.pure
legend-pure-code-compiled-core/src/main/resources/core/relational/relationalMappingExecution.pure
legend-pure-code-java-compiled-core/pom.xml
legend-pure-m2-store-relational/pom.xml
legend-pure-m2-store-relational/src/main/java/org/finos/legend/pure/m2/relational/JavaPlaceholder.java
legend-pure-m2-store-relational/src/main/resources/platform/relational/relational.pure
legend-pure-m2-store-relational/src/main/resources/platform/relational/relationalMapping.pure
legend-pure-maven-compilation-par/pom.xml
legend-pure-runtime-java-engine-compiled/pom.xml
legend-pure-runtime-java-extension-dsl-mapping/pom.xml
legend-pure-runtime-java-extension-external-json/pom.xml
pom.xml

move relational meta models to legend-pure

move relational meta models to legend-pure

---

legend-pure-code-compiled-core/pom.xml

add legend-pure-m2-store-relational to code-compiled-core module

add legend-pure-m2-store-relational to code-compiled-core module

---

legend-pure-m2-store-relational/src/main/resources/platform/relational/relational.pure

add owner property to the milestoning metamodel

add owner property to the milestoning metamodel

---

legend-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/extension/extension.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/invocations/execution.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/models/metamodel.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/mapping.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/store.pure

add extensions for externalizing relational code

add extensions for externalizing relational code

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/graphFetch/tests/testGraphFetchResultSourcing.pure

test for graphFetchResultSourcing

test for graphFetchResultSourcing

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/executionPlan/tests/executionPlanTest.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/relationalExtension.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/relationalMappingExecution.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tds/tests/testTDSJoin.pure

fix tds join issue impacting use cases where properties are mapped to columns via joins or dyna function

fix tds join issue 

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/postprocessor/postProcessor.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/relationalExtension.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/relationalMappingExecution.pure

move PostProcessorResult and executeInDb, loadCsvToDbTable helper functions

move helper functions and PostProcessorResult

---

legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/compiler/PureJavaCompileException.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/FunctionProcessor.java

Fixes for exceptions for externalizable functions

Fixes for exceptions for externalizable functions

---

legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_18_0/transfers/valueSpecification.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_19_0/transfers/valueSpecification.pure

Fix the bug for the function of AppliedFunction. The function of AppliedFunction should not contain the function signature.

Fix the bug for the function of AppliedFunction

---

legend-pure-code-compiled-core/src/main/resources/core/external/format/yaml/metamodel.pure
legend-pure-code-compiled-core/src/main/resources/core/external/format/yaml/serialization_yamlToString.pure
legend-pure-code-compiled-core/src/main/resources/core/external/format/yaml/tests/testtoyaml.pure
legend-pure-code-compiled-core/src/main/resources/core/json/fromJSONSchema.pure
legend-pure-code-compiled-core/src/main/resources/core/json/jsonSchema.pure
legend-pure-code-compiled-core/src/main/resources/core/json/jsonSchemaConstraints.pure
legend-pure-code-compiled-core/src/main/resources/core/json/tests/sharedSchema.pure
legend-pure-code-compiled-core/src/main/resources/core/json/tests/testFromJSONSchema.pure
legend-pure-code-compiled-core/src/main/resources/core/json/tests/testToJsonSchema.pure

add support for open api yaml generation

add features for json schema generation and import

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/milestoning/tests/businessDateMilestoningSetUp.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/milestoning/tests/milestoningModel.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/milestoning/tests/testMilestoningContextPropagation.pure

Add one test for the date propagation plus inheritance issue on the Pure side

Add one test for the date propagation plus inheritance issue on the Pure side

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure

Fixed by adding support in SQLQueryToString.pure

MemSQL support for modulus operator (#214)

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tests/mapping/sqlFunction/testSqlFunctionsInMapping.pure

Based on https://docs.snowflake.com/en/sql-reference/functions/to_char.html

Snowflake support for convertVarchar128 (#205)

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/functions/tests/projection/testDateFilters.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/transform/fromPure/tests/testToSQLString.pure

add support for microsecond in sql for adjust function

add support for microsecond in sql for adjust function

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/runtime/connection/datasourceSpecification.pure

add quotedIdentifiersIgnoreCase property to snowflake datasourceSpec

add quotedIdentifiersIgnoreCase property to snowflake datasourceSpec

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelations.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/lineage/scanRelations/scanRelationsTests.pure

fix Relation Tree generation for no-column tdsJoin

fix Relation Tree generation for no-column tdsJoin

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/milestoning/tests/testMilestoningContextPropagation.pure

Exclude the datePropagation with inheritance test from Alloy

Exclude the datePropagation with inheritance test from Alloy

---

legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/stringLibrary.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/stringLibraryTests.pure

add support for indexOf with fromIndex for java code-gen

add support for indexOf with fromIndex for java code-gen

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/functions/tests/testObjectReferenceIn.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/graphFetch/tests/testSimpleRelationalGraphFetch.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tests/mapping/sqlFunction/testSqlFunctionsInMapping.pure
legend-pure-code-compiled-core/src/main/resources/core/external/format/avro/tests/testAvroSchemaGenerator.pure
legend-pure-code-compiled-core/src/main/resources/core/external/format/protobuf/tests/transformation_tests.pure
legend-pure-code-compiled-core/src/main/resources/core/json/tests/sharedSchema.pure
legend-pure-code-compiled-core/src/main/resources/core/json/tests/testToJsonSchema.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/booleanLibraryTests.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/metaLibraryTests.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/planConventions/test/unitLibraryTests.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/constraints.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/simpleObject.pure

update server version tag to v1_20_0

update serverVersion tag to v1_20_0

---

.gitignore
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/models/metamodel_connection.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/transfers/connection_relational.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/runtime/connection/authenticationStrategy.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/runtime/connection/datasourceSpecification.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/tests/testBigQueryCompatibility.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tests/relationalSetUp.pure
legend-pure-m2-store-relational/src/main/resources/platform/relational/relationalRuntime.pure

Add support for BigQuery

---

legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetch_routing.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testRouting.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/simple.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/router/router_builder.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/router/router_cluster.pure

fix cross-store routing for graph

fix cross-store routing for graph

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/graphFetch/tests/testCrossStoreGraphFetch.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure

Externalize cross-store tests and fix cross-store with explosion

Externalize cross-store tests and fix cross-store with explosion

---

legend-pure-code-compiled-core/src/main/resources/core/external/language/morphir/metamodel.pure
legend-pure-code-compiled-core/src/main/resources/core/external/language/morphir/serialization.pure
legend-pure-code-compiled-core/src/main/resources/core/external/language/morphir/tests/transformAndSerializeTests.pure
legend-pure-code-compiled-core/src/main/resources/core/external/language/morphir/transform.pure

 Externalize Morphir

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tests/mapping/sqlFunction/testSqlFunctionsInMapping.pure

Use Db Type to determine data format in query

Use Db Type to determine data format in query

---

legend-pure-code-compiled-core/src/main/resources/core/pure/extensions/extension.pure

Revert "prefetch serializer extesnion"

---

legend-pure-code-compiled-core-external-format-flatdata/src/main/resources/core_external_format_flatdata/binding/validation.pure
legend-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/binding/validation.pure
legend-pure-code-compiled-core-servicestore/pom.xml
legend-pure-code-compiled-core-servicestore/src/main/java/org/finos/legend/pure/code/core/CoreServiceStoreCodeRepositoryProvider.java
legend-pure-code-compiled-core-servicestore/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore.definition.json
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/metamodel/metamodelDiagram.pure
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/metamodel/serviceStore.pure
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/metamodel/serviceStoreMapping.pure
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/metamodel/serviceStoreRuntime.pure
legend-pure-code-java-compiled-core/pom.xml
pom.xml

Add service store metamodels

---

legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/transfers/valueSpecification.pure

Resolve the imports inside function: Keep the full path of non-meta Applied Function

Resolve the imports inside function: Keep the full path of non-meta Applied Function

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/tests/testBigQueryCompatibility.pure

This PR fixes the following : 
1/ Relocate tests to a new package 
2/ Add support and tests for date/datetime literal processing

Bigquery fix

---

legend-pure-code-compiled-core-external-format-flatdata/src/main/resources/core_external_format_flatdata/protocol_v1_21_0.pure
legend-pure-code-compiled-core-external-format-xml/src/main/resources/core_external_format_xml/protocol_v1_21_0.pure
legend-pure-code-compiled-core-external-shared/src/main/resources/core_external_shared/protocol_v1_21_0.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/v1_21_0/extension/extension.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/v1_21_0/extension/extension_relational.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/v1_21_0/invocations/execution_relational_execute.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/v1_21_0/invocations/execution_relational_testData.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/v1_21_0/models/executionPlan_relational.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/v1_21_0/models/metamodel_connection.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/v1_21_0/models/metamodel_relational.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/v1_21_0/models/results_relational.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/v1_21_0/models/testData_relational.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/v1_21_0/transfers/connection_relational.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/v1_21_0/transfers/metamodel_relational.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/extension/extension.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/invocations/execution.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/invocations/testLoadModels.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/models/diagram.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/models/executionPlan.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/models/metamodel.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/models/results.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/scan/buildBasePureModel.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/scan/buildPureModelAsText.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/scan/testBuildPureModel.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/transfers/executionPlan.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/transfers/mapping.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/transfers/metamodel.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/transfers/store.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/v1_21_0/transfers/valueSpecification.pure

This PR releases protocol v1_21_0

Release protocol v1_21_0

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/helperFunctions/databaseHelperFunctions.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/helperFunctions/tests/testDdlGeneration.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/helperFunctions/toDDL.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tests/testModel/simpleTestModel.pure

Add quoting for H2 column reserved words to be compatible with newer versions of H2

Quote H2 Reserved Column Names and use DB type in DB helper func

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/tests/testBigQueryCompatibility.pure

Improve SQL generation logic for variables

Improve SQL generation logic for variables

---

legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/pureToServiceStoreQuery/pureToServiceStoreQuery.pure
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/router/router_extension.pure
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/serviceStoreMappingExecution.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure

Add support for service store union

Add support for service store union

---

legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/simpleObject.pure

Fix M2M assert tests to work from protocol v1_19_0

Fix M2M Assert function tests

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/transfers/metamodel_relational.pure

revertMilestoningTransform on properties when serializing mapping to protocol

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tds/tests/testTDSWindowColumn.pure

Update previous vx_x_x versioned alloy test to latest pure protocol version.

Update previous vx_x_x versioned alloy test to latest pure protocol version.

---

legend-pure-code-compiled-core/src/main/resources/core/pure/protocol/vX_X_X/models/diagram.pure

sync between engine's and pure's diagram model

sync between engine's and pure's diagram model 

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/functions/tests/projection/testProjectWithWindowColumns.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tds/tests/testTDSWindowColumn.pure

Add Snowflake to supported database type list for generating window aggregations

Allow window aggregations to be performed in Snowflake

---

legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/simpleObject.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/simple.pure

Fix a spelling error in a test mapping name

Fix a small typo

---

legend-pure-test-reports/pom.xml
pom.xml

Adding the nexus staging maven plugin to allow for easy deployments to Maven Central

Adding nexus staging plugin

---

legend-pure-code-compiled-core/src/main/resources/core/pure/persistence/metamodel.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/persistence/metamodel_diagram.pure

Specification for writing the result of an engine service call to a persistent store.

Initial version of persistence model.

---

legend-pure-code-compiled-core/src/main/resources/core/pure/persistence/metamodel.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/persistence/metamodel_diagram.pure

Update model based on requirements introduced by different backends.

Refine persistence model

---

legend-pure-code-compiled-core/src/main/resources/core/json/jsonSchema.pure
legend-pure-code-compiled-core/src/main/resources/core/json/tests/sharedSchema.pure

enable json schema collection option in studio file generation

add schema collection support

---

legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphExtension.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/tests/testSourceTreeCalc.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/m2m/tests/legend/simpleObject.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/store/platform/executionPlan/javaRuntime/serialize.pure

Fix source tree calculation in case of inheritance and flattening

Fix source tree calculation in case of inheritance and flattening

---

legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/metamodel/serviceStore.pure
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/protocols/pure/vX_X_X/models/metamodel_serviceStore.pure
legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/protocols/pure/vX_X_X/transfers/metamodel_serviceStore.pure

Add support for optional parameters for service store (ref - https://swagger.io/docs/specification/describing-parameters/)

Add support for optional parameters for service store

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/models/metamodel_connection.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/transfers/connection_relational.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/runtime/connection/authenticationStrategy.pure

Add GCP Workload Identity Federation Using AWS Auth Strategy

Add GCP Workload Identity Federation Using AWS Auth Strategy

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/models/metamodel_connection.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/protocols/pure/vX_X_X/transfers/connection_relational.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/runtime/connection/datasourceSpecification.pure

add support for Redshift  datasource specification

add support for Redshift  datasource specification

---

legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/AbstractCompiledStateIntegrityTest.java

Add a compiled state integrity test to ensure all LambdaFunctions have unique names. The names are used in generated Java code as ids to look up the LambdaFunctions, and so they must be unique.

Add a test to ensure all LambdaFunctions have unique names

---

legend-pure-code-compiled-core-servicestore/src/main/resources/core_servicestore/metamodel/serviceStore.pure

ref - https://swagger.io/docs/specification/describing-parameters/

Add support for header parameters via service store

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/pureToSQLQuery/pureToSQLQuery_union.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/tests/mapping/union/testUnion.pure

Revert "Export default literal values for pk cols in union dataflow"

---

legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/router/router_extension.pure
legend-pure-code-compiled-core-relational/src/main/resources/core_relational/relational/sqlQueryToString/SQLQueryToString.pure

More refactoring requests will follow this.

SqlQueryToString refactoring: introduce db extension mechanism

---

legend-pure-code-compiled-core/src/main/resources/core/pure/executionPlan/javaPlatform/shared/constraints.pure

Add sorting for defects addition to result

Add sorting for defects addition to result

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/repository/CodeRepository.java

Fix some typos in comments in CodeRepository.

Fix typos in comments in CodeRepository

---

legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/metaExtension.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/tests/metaExtension.pure

Added recursion for ConcreteFuncDef in findExpressionsForFunctionInValueSpecification functionality

Added recursion for ConcreteFuncDef in findExpressionsForFunctionInValueSpecification functionality

---

legend-pure-code-compiled-core/src/main/resources/core/pure/graphFetch/graphFetchExecutionPlan.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/mapping/modelToModel.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/router/router_cluster.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/router/router_main.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/store/platform/executionPlan/javaRuntime/executionPlanNodes/platform/platform.pure
legend-pure-code-compiled-core/src/main/resources/core/pure/store/platform/executionPlan/javaRuntime/executionPlanNodes/platform/serialize.pure

Add support for union on more than 2 sets

Add support for union on more than 2 sets

---

legend-pure-code-compiled-core/src/test/java/org/finos/legend/pure/code/core/TestIdBuilderCore.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/IdBuilder.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/TestIdBuilder.java

Allow custom id builder functions so that non-platform types can have custom ids.

Allow custom id builder functions

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/IncrementalCompiler.java

Fix sonar illegal type cast bug

Fix sonar illegal type cast bug

---

legend-pure-maven-java-compiled/src/main/java/org/finos/legend/pure/maven/javaCompiled/PureCompiledJarMojo.java

Clean up PureCompiledJarMojo, especially with regards to the logging and classloader.

Clean up PureCompiledJarMojo

---

legend-pure-m2-dsl-mapping/src/main/resources/platform/pure/mapping.pure
legend-pure-m3-core/src/main/resources/platform/pure/m3.pure
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/runtime/binary/TestBinaryModelRepositorySerializer.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/runtime/binary/TestBinaryModelSourceSerializer.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/lineinfo/TestLineInfo.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassInterfaceProcessor.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/TestFunctionReturnMultiplicity.java

testable mechanism refactor

---

legend-pure-m2-dsl-mapping/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/validator/PureInstanceSetImplementationValidator.java
legend-pure-m2-dsl-mapping/src/test/java/org/finos/legend/pure/m2/ds/mapping/test/TestModelMapping.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/multiplicity/Multiplicity.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/multiplicity/TestMultiplicity.java

fix_union_property_mapping_multiplicity_checks

fix_union_property_mapping_multiplicity_checks

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/M3Paths.java

Update ClusteredValueSpecification path

Update ClusteredValueSpecification path

---

legend-pure-ide-light/pom.xml
legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/api/Suggestion.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/Source.java

Bring over changes from https://github.com/finos/legend-studio/pull/1794 for stability improvements, basic change detection, and support for variable suggestions

Pure IDE: more improvements

---

legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/PureIDEServer.java

When we remove some repos from CodeRepositorySet, when it is build a failure is thrown if required dependecies where removed.

Process classpath repos directly to avoid validation failures from CodeRepositorySet

---

legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/lang/AbstractTestNewAtRuntime.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/core/lang/New.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Reactivator.java

Fix Reactivate on new without keyExpressions

Fix Reactivate on new without keyExpressions

---

.github/workflows/build.yml

Do not ignore test failures in build

Do not ignore test failures in build

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/generator/par/PureJarGenerator.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/orchestrator/JavaCodeGeneration.java

Allow loading extra repositories from file path in Java code generation

Allow loading extra repositories from file path in Java code generation

---

legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CompiledSupport.java
legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/basics/collection/Sort.java

Improve sorting implementations in interpreted and compiled modes.

Improve sorting implementations in interpreted and compiled modes

---

legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/compiler/ClassJavaSource.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/compiler/MemoryClassLoader.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/compiler/MemoryFileManager.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/PreCompiledPureGraphCache.java

Clean up in memory class loaders and pre-compiled graph cache

Clean up in memory class loaders and pre-compiled graph cache

---

legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/AbstractTestPureDBFunction.java
pom.xml

Upgrade H2 version to 1.4.200

---

legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/AbstractTestPureDBFunction.java

Fix tests so they do not depend on a particular H2 version.

Fix tests so they do not depend on a particular H2 version

---

legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/compiler/StringJavaSource.java

Ensure we call end on Deflater and Inflater instances

Ensure we call end on Deflater and Inflater instances

---

legend-pure-m3-core/src/main/resources/platform/pure/profile.pure
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/modeling/function/TestFunctionReturnMultiplicity.java

Add NotImplementedFunction stereotype for functionType profile

Add NotImplementedFunction stereotype for functionType profile

---

legend-pure-m2-store-relational-pure/src/main/resources/platform_store_relational/relationalRuntime.pure

Add Trino DatabaseType

---

legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/compiler/MemoryFileManager.java

Remove unused method with bug from MemoryFileManager

Remove unused method with bug from MemoryFileManager

---

legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/extension/BaseCompiledExtension.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/extension/CompiledExtension.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CoreExtensionCompiled.java
legend-pure-runtime-java-extension-dsl-diagram/src/main/java/org/finos/legend/pure/runtime/java/extension/dsl/diagram/compiled/DiagramExtensionCompiled.java
legend-pure-runtime-java-extension-dsl-graph/src/main/java/org/finos/legend/pure/runtime/java/extension/dsl/graph/compiled/GraphExtensionCompiled.java
legend-pure-runtime-java-extension-dsl-mapping/src/main/java/org/finos/legend/pure/runtime/java/extension/dsl/mapping/compiled/MappingExtensionCompiled.java
legend-pure-runtime-java-extension-dsl-path/src/main/java/org/finos/legend/pure/runtime/java/extension/dsl/path/compiled/PathExtensionCompiled.java
legend-pure-runtime-java-extension-functions-json/src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/compiled/JsonExtensionCompiled.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsExtensionCompiled.java
legend-pure-runtime-java-extension-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/compiled/RelationalExtensionCompiled.java

Add default implementations for CompiledExtension

Add default implementations for CompiledExtension

---

legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Pure.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/map/PureEqualsHashingStrategy.java

Minor improvements to Pure class, particular for Pure.removeDuplicates

Minor improvements to Pure class

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/Instance.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/ProcessorSupport.java

These interfaces are used for interoperability on the mixin support: https://github.com/finos/legend-engine/pull/1574

Delegate Instance method to process support to be able to intercept setter/getter calls

---

legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/compiler/PureJavaCompiler.java

Cache classpath in PureJavaCompiler so it doesn't need to be recomputed for every compilation.

Cache classpath in PureJavaCompiler

---

legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/compiler/Compile.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/compiler/MemoryFileManager.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/compiler/PureJavaCompiler.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/Generate.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/GenerateAndCompile.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaStandaloneLibraryGenerator.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/orchestrator/JavaCodeGeneration.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/TestJavaStandaloneLibraryGenerator.java

Fix internal Javac flag. Imrpove Java compilation logs.

Fix internal Javac flag. Imrpove Java compilation logs.

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/validation/validator/PropertyValidator.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/M3Paths.java
legend-pure-m3-core/src/main/resources/platform/pure/grammar/m3.pure
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/lineinfo/TestLineInfo.java
legend-pure-m4/pom.xml
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/ModelRepository.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/BinaryCoreInstance.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/PrimitiveCoreInstance.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/TypeProcessor.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/modeling/function/TestFunctionReturnMultiplicity.java

Revert "Remove Binary data type"

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/AbstractMultipleRepositoryCodeStorage.java

Allow update of repositories in CodeStorage

Allow update of repositories in CodeStorage

---

legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/api/FileManagement.java

fix a regression for file read-only status introduced by https://github.com/finos/legend-pure/pull/689

pure ide: fix problem with read-only status reporting for file management

---

pom.xml

Upgrade jacoco maven plugin to 0.8.10

Upgrade jacoco maven plugin to 0.8.10

---

pom.xml

Upgrade nexus-staging-maven-plugin to 1.6.13

Upgrade nexus-staging-maven-plugin to 1.6.13

---

legend-pure-m2-store-relational-pure/src/main/resources/platform_store_relational/relationalRuntime.pure

It adds a new enum for SingleStore DB

Introduce new DB type SingleStore

---

legend-pure-runtime-java-extension-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/shared/connectionManager/TestDatabaseConnect.java

Avoid setting the H2 connection with 2.x only properties if the H2 dependency is forced to 1.4.200.  This will give projects importing legend time to migrate to 2.x

Support legacy 1.4.200 H2

---

legend-pure-m2-functions-pure/src/main/resources/platform_functions/date/dayOfYear.pure
legend-pure-m2-functions-pure/src/main/resources/platform_functions/math/cbrt.pure
legend-pure-m2-functions-pure/src/main/resources/platform_functions/string/lTrim.pure
legend-pure-m2-functions-pure/src/main/resources/platform_functions/string/rTrim.pure
legend-pure-runtime-java-extension-functions/pom.xml
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsExtensionCompiled.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsHelper.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/date/DayOfYear.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/math/Cbrt.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/LTrim.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/RTrim.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/FunctionExtensionInterpreted.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/natives/date/DayOfYear.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/natives/math/Cbrt.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/natives/string/LTrim.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/natives/string/RTrim.java

String: ltrim, rtrim
Math: cbrt
Date: dayOfYear

Assortment of new functions

---

legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/api/FileManagement.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/RepositoryRevisionCache.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/PureModelVersion.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/VersionControlledClassLoaderCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/composite/CompositeCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/vcs/Revision.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/vcs/VersionControlledCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/binary/BinaryModelRepositorySerializer.java

This reverts commit 2959b0e5ff53e91274a3a1fd51ca730344333d97.

Revert "Switch VCS revisions to String from Long (#710)"

---

legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/string/AbstractTestSubstring.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/NativeFunctionProcessor.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/basics/string/Substring2.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/basics/string/Substring3.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/string/TestSubstringCompiled.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/string/TestSubstringInterpreted.java

- add test for substring native function

fix substring function in pure compiled mode for different signatures

---

legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/api/FileManagement.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/RepositoryRevisionCache.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/PureModelVersion.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/VersionControlledClassLoaderCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/composite/CompositeCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/vcs/Revision.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/vcs/VersionControlledCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/binary/BinaryModelRepositorySerializer.java

Change representation of VCS revisions from long to String

Use strings for VCS Revisions

---

legend-pure-m2-store-relational-pure/src/main/resources/platform_store_relational/relationalRuntime.pure

Add Spark to DatabaseType Enum

Add Spark to DatabaseType Enum 

---

legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/string/AbstractTestChar.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/string/AbstractTestIndexOf.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CompiledSupport.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsExtensionCompiled.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/IndexOf.java
legend-pure-runtime-java-extension-functions/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/IndexOfWithFrom.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/string/TestCharCompiled.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/string/TestIndexOfCompiled.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/string/TestCharInterpreted.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/string/TestIndexOfInterpreted.java

Fix indexOf and char in compiled eval flow

Fix indexOf and char in compiled eval flow

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/composite/CompositeCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/vcs/MutableVersionControlledCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/PureRuntime.java

Add update function which takes in a String revision

Pure Runtime and VCS fixes

---

pom.xml

Update timeout for Sonatype Nexus deployment

Update timeout for Sonatype Nexus deployment

---

legend-pure-ide-light/src/main/java/org/finos/legend/pure/ide/light/api/Service.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/function/FunctionDescriptor.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/TestFunctionDescriptor.java

Fix Function Descriptor to ID

---

.gitignore
legend-pure-m3-bootstrap-generator/pom.xml
legend-pure-m3-bootstrap-generator/src/main/java/org/finos/legend/pure/m3/bootstrap/generator/CoreInstanceGenerator.java
legend-pure-m3-bootstrap-generator/src/main/java/org/finos/legend/pure/m3/tools/FileTools.java
legend-pure-m3-bootstrap-generator/src/main/java/org/finos/legend/pure/m3/tools/GeneratorTools.java
legend-pure-m3-core/pom.xml
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/generator/bootstrap/M3CoreInstanceGenerator.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/generator/par/PureJarGenerator.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/generator/par/PureJarSerializer.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/CodeStorageNode.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/RepositoryCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/ClassLoaderCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/ClassLoaderDirectoryNode.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/ClassLoaderFileNode.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/ClassLoaderPathFileNode.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/ClassLoaderURLFileNode.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/composite/CompositeCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/empty/EmptyCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/fs/FSCodeStorage.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/binary/BinaryRepositorySerializer.java
legend-pure-m4/src/test/java/org/finos/legend/pure/m4/primitives/TestPureDate.java
legend-pure-maven-generation-java/src/main/java/org/finos/legend/pure/maven/javaCompiled/PureCompiledJarMojo.java
legend-pure-maven-generation-par/src/main/java/org/finos/legend/pure/maven/par/PureJarMojo.java
legend-pure-runtime-java-engine-compiled/pom.xml
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/orchestrator/JavaCodeGeneration.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/orchestrator/JavaModelFactoryGenerator.java

Preparatory changes for better incremental build support with the code generators.
- Add support for last modified information on code storage 
- Update generators to support checking file modification times to skip where possible

Preparatory changes for better incremental build support with the code generators

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/CodeStorageNode.java

Fix CodeStorageNode interface with default method

Fix CodeStorageNode interface with default method

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/ClassLoaderCodeStorage.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/ClassLoaderCodeStorageNode.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/ClassLoaderDirectoryNode.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/ClassLoaderFileNode.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/ClassLoaderPathFileNode.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/ClassLoaderURLFileNode.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/VersionControlledClassLoaderCodeStorage.java

Fix bug in ClassLoaderCodeStorage with handling jar URLs in Windows. In passing, clean up some of the class loader code storage code.

Fix bug in ClassLoaderCodeStorage with handling jar URLs in Windows

---

legend-pure-m3-bootstrap-generator/src/main/java/org/finos/legend/pure/m3/tools/FileTools.java

FileTools: fix logic in finding oldest modified dirs

FileTools: fix logic in finding oldest modified dirs

---

legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/Version.java

Make Version.version protected for use in subclasses

Make Version.version protected

---

legend-pure-m3-core/src/main/antlr4/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/core/M3CoreParser.g4
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/function/FunctionDescriptor.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/function/InvalidFunctionDescriptorException.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/TestFunctionDescriptor.java
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/meta/AbstractTestFunctionDescriptorToId.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/meta/TestFunctionDescriptorToIdCompiled.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/meta/TestFunctionDescriptorToId.java

Update FunctionDescriptor to allow a richer grammar. In particular, allow type arguments.

Update FunctionDescriptor to allow a richer grammar

---

legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/collection/map.pure
legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/collection/AbstractTestMap.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Pure.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Reactivator.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/modeling/function/TestFunctionReturnMultiplicity.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/collection/TestMapCompiled.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/collection/TestMap.java

Fix a bug with dynamic evaluation of automap with 0..1 property, and add tests for the case. In passing, improve exception handling in the relevant code.

Fix bug with dynamic evaluation of automap with 0..1 property

---

legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/modeling/function/TestFunctionReturnMultiplicity.java

Make TestFunctionReturnMultiplicity less brittle, so that it doesn't start failing every time the synthetic id of Class changes.

Make TestFunctionReturnMultiplicity less brittle

---

legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/string/AbstractTestFormat.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/basics/lang/Eval.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/basics/lang/Evaluate.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/basics/meta/GenericType.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/basics/string/Format.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CompiledSupport.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CoreExtensionCompiled.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Pure.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/PureStringFormat.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/string/TestFormat.java
legend-pure-runtime-java-extension-functions/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/string/TestFormat.java

Fix compiled implementation of format, which previously did not work when used in eval or evaluate.

Fix compiled implementation of format

---

legend-pure-runtime-java-extension-dsl-mapping/src/main/resources/META-INF/services/org.finos.legend.pure.runtime.java.compiled.extension.CompiledExtension

Fix typo in service loader declaration for MappingExtensionCompiled.

Fix typo in service loader declaration for MappingExtensionCompiled

---

legend-pure-m2-dsl-mapping-grammar/src/test/java/org/finos/legend/pure/m2/ds/mapping/test/TestModelMapping.java
legend-pure-m2-dsl-store-grammar/src/main/java/org/finos/legend/pure/m2/inlinedsl/store/processor/RelationStoreAccessorProcessor.java
legend-pure-m2-functions-pure/src/main/resources/platform_functions/meta/sourceInformation.pure
legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/serialization/grammar/v1/RelationalParser.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/Context.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_RelationType.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/Loader.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/Parser.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/ParserLibrary.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/GraphLoader.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/IncrementalCompiler.java
legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/IncrementalCompiler_New.java
legend-pure-m3-core/src/main/resources/platform/pure/basics/string/format.pure
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/tools/ConcurrentHashSet.java
legend-pure-m4/src/main/java/org/finos/legend/pure/m4/tools/SafeAppendable.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/execution/FunctionExecutionCompiled.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/JavaMethodSharedPureFunction.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/JavaMethodWithParamsSharedPureFunction.java
legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/binary/DistributedMetadataSpecification.java
legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/serialization/binary/TestDistributedMetadataSpecification.java
legend-pure-runtime-java-extension-dsl-mapping/pom.xml
legend-pure-runtime-java-extension-dsl-mapping/src/test/java/org/finos/legend/pure/runtime/java/extension/dsl/mapping/compiled/TestMappingExtensionCompiled.java

Add tests and clean up code

---

pom.xml

Move test-reports up in the build sequence

Move test-reports up in the build sequence

---

legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-pure/src/main/resources/platform_store_relational/relationalRuntime.pure

Add DuckDB to DatabaseType Enum

Add DuckDB to DatabaseType Enum

---

legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/pom.xml

Remove duplicate dependency in pom

Clean up pom

---

pom.xml

Clean up main pom.xml by organizing version properties and removing dependency management for no longer needed dependencies. Also remove some no longer needed exceptions to banned dependencies.

Clean up main pom.xml

---

legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/size.pure

Add tests for size of Relation

Add tests for size of Relation

---

legend-pure-core/legend-pure-m3-bootstrap-generator/src/main/java/org/finos/legend/pure/m3/bootstrap/generator/M3ToJavaGenerator.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/ListHelper.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/FloatCoreInstance.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/IntegerCoreInstance.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/PrimitiveCoreInstance.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/StringCoreInstance.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsExtensionCompiled.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsHelper.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/natives/meta/NewAssociation.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/natives/meta/NewClass.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/natives/meta/NewEnumeration.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CompiledSupport.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Pure.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassLazyImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/FunctionCache.java

Assorted minor improvements to:
- M3 Java generation
- compiled mode Java generation
- compiled mode function cache
- primitive core instances
- collection helper functions

Assorted minor improvements

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/inference/TypeInferenceContext.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/Support.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_RelationType.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/inference/TestFunctionTypeInference.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/generictype/TestTypeResolutionForIf.java
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/concatenate.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/drop.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/extend.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/filter.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/groupBy.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/join.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/limit.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/project.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/rename.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/select.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/slice.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/sort.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/tests/composition.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/tests/tests.pure

Fix compiler. Type inference for Function of Functions

Fix compiler. Type inference for Function of Functions

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/inference/TypeInferenceContext.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/Support.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_RelationType.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/inference/TestFunctionTypeInference.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/generictype/TestTypeResolutionForIf.java
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/concatenate.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/drop.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/extend.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/filter.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/groupBy.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/join.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/limit.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/project.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/rename.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/select.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/slice.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/sort.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/tests/composition.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/tests/tests.pure

Revert type inference changes, and add some tests to prevent regression on some previously untested cases.

Revert type inference changes

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/inference/TestFunctionTypeInference.java

Add more type inference tests about chaining calls to map.

Add more type inference tests

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/inference/TypeInferenceContext.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/Support.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_RelationType.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/inference/TestFunctionTypeInference.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/generictype/TestTypeResolutionForIf.java
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/concatenate.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/drop.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/extend.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/filter.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/groupBy.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/join.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/limit.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/project.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/rename.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/select.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/slice.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/functions/sort.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/tests/composition.pure
legend-pure-functions/legend-pure-functions-relation/legend-pure-m2-functions-relation-pure/src/main/resources/platform_functions_relation/relation/tests/tests.pure

Recommit reverted type inferences changes with some fixes to make sure new tests pass.

Type inference fixes

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/inference/TypeInferenceContext.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/inference/TestFunctionTypeInference.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/generictype/TestTypeResolutionForIf.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CompiledSupport.java

Add more inference tests

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/function/inference/TestFunctionTypeInference.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/generictype/TestTypeResolutionForIf.java

Clean up recent changes to type inference tests

Clean up test changes

---

legend-pure-core/legend-pure-m3-core/src/main/antlr4/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/core/M3CoreParser.g4
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/GraphPath.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/GraphPathFilters.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/GraphPathIterable.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/ResolvedGraphPath.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/GraphStatistics.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/PackageTreeIterable.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/navigation/graph/TestGraphPath.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/navigation/graph/TestGraphPathIterable.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/CompiledStateIntegrityTestTools.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/tools/TestPackageTreeIterable.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/tools/AbstractLazySpliterable.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/tools/GraphNodeIterable.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/tools/GraphWalkFilterResult.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/tools/GraphWalkFilters.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/binary/DistributedBinaryFullGraphSerializer.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/binary/DistributedBinaryRepositorySerializer.java

Improvements to GraphPath, GraphPathIterable, GraphNodeIterable, and PackageTreeIterable

Graph path and traversal improvements

---

legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/SourceInformation.java
legend-pure-core/legend-pure-m4/src/test/java/org/finos/legend/pure/m4/coreinstance/TestSourceInformation.java

Add several methods to SourceInformation: intersects, isValid, and a suite of methods for comparing source positions (i.e., line-column pairs).

SourceInformation improvements

---

legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/antlr4/org/finos/legend/pure/m2/relational/serialization/grammar/v1/antlr/RelationalParser.g4
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/serialization/grammar/v1/antlr/RelationalGraphBuilder.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/incremental/TestDatabase.java

- Improvement
Ability to tag stores with profiles to be able to identify and route during plan generation

Stereotypes support for Relational Databases

---

legend-pure-core/legend-pure-m3-bootstrap-generator/src/main/java/org/finos/legend/pure/m3/bootstrap/generator/M3ToJavaGenerator.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/coreinstance/CoreInstanceFactoryRegistry.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/CoreInstanceFactoriesRegistry.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/IncrementalCompiler.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/execution/FunctionExecutionCompiled.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/factory/JavaModelFactoryRegistry.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/factory/JavaModelFactoryRegistryLoader.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaSourceCodeGenerator.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/orchestrator/JavaModelFactoryGenerator.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassProcessor.java

Improvements to CoreInstanceFactoryRegistry and core M3 Java generation

Improvements to CoreInstanceFactoryRegistry and core M3 Java generation

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/PackageableElement/PackageableElement.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/packageablelement/TestPackageableElement.java
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-runtime-java-extension-compiled-dsl-tds/pom.xml
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/ReflectiveCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassLazyImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/valuespecification/ValueSpecificationProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/TestReflectiveCoreInstance.java

Add compiled mode implementation of getRealKeyByName.

Add compiled mode implementation of getRealKeyByName

---

legend-pure-functions/legend-pure-functions-base/legend-pure-m2-functions-base-pure/src/main/resources/platform_functions/string/jaroWinklerSimilarity.pure
legend-pure-functions/legend-pure-functions-base/legend-pure-m2-functions-base-pure/src/main/resources/platform_functions/string/levenshteinDistance.pure
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/pom.xml
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsExtensionCompiled.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsHelper.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/JaroWinklerSimilarity.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/LevenshteinDistance.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/pom.xml
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/FunctionExtensionInterpreted.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/natives/string/JaroWinklerSimilarity.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/natives/string/LevenshteinDistance.java

https://github.com/finos/legend-pure/pull/740 was reverted, committing it again

Fuzzy matching - Jaro-Winkler similarity and Levenshtein distance support

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/coreinstance/helper/AnyStubHelper.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/PrimitiveUtilities.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/GraphPath.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/CodeStorageTools.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/coreinstance/helper/TestAnyStubHelper.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/navigation/graph/TestGraphPath.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/filesystem/TestCodeStorageTools.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/tools/TestPrimitiveUtilities.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/binary/AbstractSimpleBinaryReader.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/binary/AbstractSimpleBinaryWriter.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/binary/ByteBufferBinaryReader.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/binary/ByteCollectionBinaryWriter.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/binary/ByteListBinaryReader.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/binary/ReadableByteChannelReader.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/binary/StreamBinaryReader.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/binary/StreamBinaryWriter.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/binary/WritableByteChannelWriter.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/binary/DistributedBinaryFullGraphSerializer.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/binary/DistributedBinaryRepositorySerializer.java

Various minor improvements to binary readers/writers, CodeStorageTools, GraphPath, PrimitiveUtilities, and AnyStubHelper

Various minor improvements

---

legend-pure-functions/legend-pure-functions-base/legend-pure-m2-functions-base-pure/src/main/resources/platform_functions/math/cbrt.pure
legend-pure-functions/legend-pure-functions-base/legend-pure-m2-functions-base-pure/src/main/resources/platform_functions/math/pow.pure

Fix tolerance for some Math tests

Fix tolerance for some Math tests

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/filesystem/repository/CodeRepositoryProviderHelper.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/IncrementalCompiler_New.java
legend-pure-functions/legend-pure-functions-relation/legend-pure-runtime-java-extension-shared-functions-relation/src/main/java/org/finos/legend/pure/runtime/java/extension/external/relation/shared/TestTDS.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CompiledSupport.java

Fix some Sonar bugs

---

legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsExtensionCompiled.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsHelper.java
legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-interpreted-functions-base/src/main/java/org/finos/legend/pure/runtime/java/extension/functions/interpreted/natives/math/Random.java

Make the interpreted and compiled implementations of random secure by using SecureRandom, rather than the default (insecure) Random.

Make random implementation secure

---

legend-pure-functions/legend-pure-functions-base/legend-pure-runtime-java-extension-compiled-functions-base/pom.xml

Reenable compiled mode tests

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/m3.pure

Make DefaultValue extend ModelElement instead of PackageableElement

Make DefaultValue extend ModelElement instead of PackageableElement

---

legend-pure-core/legend-pure-m3-core/src/main/antlr4/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/core/M3CoreParser.g4
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/valuespecification/FunctionExpressionProcessor.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/GenericType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_Column.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_RelationType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/runtime/PureRuntime.java
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/aggColSpec2.pure
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/aggColSpecArray2.pure
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/funcColSpec2.pure
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/funcColSpecArray2.pure
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/TestClassLoaderCodeStorage.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/relation/TestColumnBuilders.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/relation/TestRelationTypeInference.java
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-grammar/src/main/java/org/finos/legend/pure/m2/inlinedsl/tds/TDSExtension.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/serialization/grammar/v1/RelationalParser.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/TestRelationAccessor.java

Improve Relation time system to support OLAP functions

Improve Relation type system to support OLAP functions

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/frame.pure
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/aggColSpec2.pure
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/aggColSpecArray2.pure
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/funcColSpec2.pure
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/funcColSpecArray2.pure
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/filesystem/usercodestorage/classpath/TestClassLoaderCodeStorage.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/relation/TestColumnBuilders.java

Add support for Frame in OLAP operations

Add support for Frame in OLAP operations

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/m3.pure

Make Measure extend DataType instead of Type

Make Measure extend DataType

---

legend-pure-maven/legend-pure-maven-generation-java/src/main/java/org/finos/legend/pure/maven/javaCompiled/PureCompiledJarMojo.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/Generate.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/GenerateAndCompile.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaSourceCodeGenerator.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaStandaloneLibraryGenerator.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/orchestrator/JavaCodeGeneration.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/TestJavaStandaloneLibraryGenerator.java

add feature to skip generation of java pure tests

add feature to skip generation of java pure tests 

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/aggColSpec.pure
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/aggColSpec2.pure
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/aggColSpecArray.pure
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/aggColSpecArray2.pure
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/relation/TestColumnBuilders.java

Update from changes in https://github.com/finos/legend-pure/pull/762 after refactoring in https://github.com/finos/legend-pure/pull/840
Closes https://github.com/finos/legend-pure/pull/762

Allow nullable aggregation functions in aggColSpec

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/essential/lang/creation/dynamicNew.pure
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/essentials/lang/creation/DynamicNew.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/grammar/lang/creation/InstantiationHelpers.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/grammar/lang/creation/New.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/grammar/lang/creation/NewWithKeyExpr.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/AbstractCompiledCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/DefaultValue.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/ClassCache.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/resources/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/core/CoreGen.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/essentials/lang/creation/DynamicNew.java

Fix Dynamic Eval with Default values

Fix Dynamic Eval with Default values

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java

Add test for validating source information overlap

Add test for validating source information overlap

---

legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-grammar/src/main/java/org/finos/legend/pure/m2/inlinedsl/tds/TDSExtension.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/testHelper/PureTestBuilderInterpreted.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-pure/src/main/resources/platform_store_relational/grammar/relational.pure

Fix Interpreted PCT Runner. Add date support for TDS. Add AsOfJoin

Fix Interpreted PCT Runner. Add date support for TDS. Add AsOfJoin

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/exception/PureAssertFailException.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/exception/PureExecutionException.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/exception/PureExecutionStreamingException.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/compiler/PureDynamicReactivateException.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/execution/sourceInformation/PureCompiledExecutionException.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/FunctionProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/map/PureCacheMapGetException.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/runtime/api/TestFunctionExecutionStart.java
legend-pure-runtime/legend-pure-runtime-java-engine-shared/src/main/java/org/finos/legend/pure/runtime/java/shared/listeners/ExecutionEndListenerStateException.java
legend-pure-runtime/legend-pure-runtime-java-engine-shared/src/main/java/org/finos/legend/pure/runtime/java/shared/listeners/ExecutionListeners.java

Make call stack optional for PureExecutionException

Make call stack optional for PureExecutionException

---

legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-pure/src/main/resources/platform_store_relational/relationalRuntime.pure

- Feature Improvement
Add query timeout to database connection.

Add query timeout to database connection

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/grammar/v1/AbstractPrimitiveParsingTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/grammar/v1/TestByteCompilation.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/grammar/v1/TestDateParsing.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/grammar/v1/TestDateTimeParsing.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/grammar/v1/TestLatestDateParsing.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/grammar/v1/TestStrictDateParsing.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/grammar/v1/TestStrictTimeParsing.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/validation/TestGeneralization.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/serialization/grammar/antlr/AntlrSourceInformation.java

More source information fixes, particularly with respect to parsing errors. Improve primitive parsing tests to assert more precise source information for errors.

More source information fixes

---

legend-pure-core/legend-pure-m3-bootstrap-generator/src/main/java/org/finos/legend/pure/m3/bootstrap/generator/M3ToJavaGenerator.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/milestoning/PropertyInstanceBuilder.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/milestoning/AbstractTestMilestoning.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/milestoning/TestMilestoningClassProcessor.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/milestoning/TestMilestoningPropertyProcessor.java

Fix inappropriate source info in milestoning properties. Improve milestoning processing tests.

Fix inappropriate source info in milestoning properties

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/inlinedsl/InlineDSL.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java
legend-pure-dsl/legend-pure-dsl-graph/legend-pure-m2-dsl-graph-grammar/src/main/java/org/finos/legend/pure/m2/inlinedsl/graph/antlr/GraphDSL.java
legend-pure-dsl/legend-pure-dsl-path/legend-pure-m2-dsl-path-grammar/src/main/java/org/finos/legend/pure/m2/inlinedsl/path/NavigationPath.java
legend-pure-dsl/legend-pure-dsl-store/legend-pure-m2-dsl-store-grammar/src/main/java/org/finos/legend/pure/m2/inlinedsl/store/RelationStoreAccessor.java
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-grammar/src/main/java/org/finos/legend/pure/m2/inlinedsl/tds/TDSExtension.java
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-grammar/src/test/java/org/finos/legend/pure/m2/inlinedsl/tds/TestTDSDSLCompilation.java
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-runtime-java-extension-compiled-dsl-tds/src/main/java/org/finos/legend/pure/runtime/java/extension/dsl/tds/compiled/TDSNativeImplementation.java
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-runtime-java-extension-interpreted-dsl-tds/src/main/java/org/finos/legend/pure/runtime/java/extension/dsl/tds/interpreted/natives/StringToTDS.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/incremental/TestRelationDatabaseAccessor.java

Fix source info for TDS and RelationStoreAccessor inline DSLs.

Fix source info for TDS and RelationStoreAccessor DSLs

---

legend-pure-core/legend-pure-m3-core/src/main/antlr4/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/core/M3CoreParser.g4
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/grammar/v1/TestM3AntlrParser.java

Fix arrow precedence parsing

---

.gs-project.yml
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-pure/src/main/resources/platform_dsl_tds/tds.pure
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-runtime-java-extension-compiled-dsl-tds/pom.xml

Create TDSRelationAccessor for PCT

Create TDSRelationAccessor for PCT

---

legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-pure/src/main/resources/platform_dsl_tds/tds.pure
legend-pure-dsl/legend-pure-dsl-tds/legend-pure-runtime-java-extension-compiled-dsl-tds/pom.xml

Revert "Create TDSRelationAccessor for PCT"

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/AssociationProcessor.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/milestoning/PropertyInstanceBuilder.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/projection/ProjectionUtil.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/unload/unbind/ClassProjectionUnbind.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/CompiledStateIntegrityTestTools.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/validation/TestGeneralization.java
legend-pure-dsl/legend-pure-dsl-graph/legend-pure-m2-dsl-graph-grammar/src/main/java/org/finos/legend/pure/m2/inlinedsl/graph/antlr/GraphAntlrTreeWalker.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/MappingParser.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/antlr/MappingGraphBuilder.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/processor/AggregationAwareProcessor.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/processor/PropertyMappingProcessor.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/processor/PureInstanceSetImplementationProcessor.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/processor/SetImplementationProcessor.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/processor/XStoreProcessor.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/serialization/grammar/v1/processor/MilestoningPropertyMappingProcessor.java

Fix source information for reference usage owners. This includes adding source information for many instances, especially generic types. Also, a test is added to ensure all reference usage owners have generic types.

Fix source info for reference usage owners

---

legend-pure-maven/legend-pure-maven-generation-pct/src/main/java/org/finos/legend/pure/maven/pct/GeneratePCTReport.java

Add PCT test class validation in maven plugin

Add PCT test class validation in maven plugin

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/GraphPathIterable.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/GraphTools.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/PackageTreeIterable.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/PackageableElementIterable.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/tools/TestPackageableElementIterable.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/tools/AbstractLazySpliterable.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/tools/GraphNodeIterable.java
legend-pure-core/legend-pure-m4/src/test/java/org/finos/legend/pure/m4/tools/TestAbstractLazySpliterable.java

Improvements to tools for navigating over the compiled graph.

Graph tool improvements

---

legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/AbstractTestPureDBFunction.java
legend-pure-store/legend-pure-store-relational/legend-pure-runtime-java-extension-compiled-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/compiled/natives/ResultSetValueHandlers.java

H2 upgrade to v2.1.214

---

legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/serialization/grammar/v1/antlr/RelationalGraphBuilder.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/TestSimpleGrammar.java

Fix multiplicity parsing for Relational local mapping properties

Fix multiplicity parsing for Relational local mapping properties

---

legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/AbstractTestPureDBFunction.java
legend-pure-store/legend-pure-store-relational/legend-pure-runtime-java-extension-compiled-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/compiled/natives/ResultSetValueHandlers.java

This reverts commit 3055282077d6f67f0ac48045a231b881b231885f.

Revert "Changes to upgrade h2 version from v1 to v2 (#940)"

---

legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/primitive/date/DateWithSubsecond.java

DateWithSubsecond change needed for timebucket calculation in legend-engine

DateWithSubsecond change needed for timebucket calculation

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/valuespecification/FunctionExpressionProcessor.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/GenericType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/Parser.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/ParserLibrary.java
legend-pure-core/legend-pure-m3-precisePrimitives/pom.xml
legend-pure-core/legend-pure-m3-precisePrimitives/src/main/java/org/finos/legend/pure/code/core/PlatformPrecisePrimitivesCodeRepositoryProvider.java
legend-pure-core/legend-pure-m3-precisePrimitives/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
legend-pure-core/legend-pure-m3-precisePrimitives/src/main/resources/platform_precise_primitives.definition.json
legend-pure-core/legend-pure-m3-precisePrimitives/src/main/resources/platform_precise_primitives/precisePrimitives.pure
legend-pure-core/pom.xml
legend-pure-dsl/legend-pure-dsl-store/legend-pure-m2-dsl-store-grammar/src/main/java/org/finos/legend/pure/m2/inlinedsl/store/processor/RelationStoreAccessorProcessor.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/pom.xml
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/serialization/grammar/v1/RelationalParser.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/TestRelationAccessor.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/incremental/TestRelationDatabaseAccessor.java
pom.xml

Move precise primitives & Fix Relation compile issues

Move precise primitives & Fix Relation compile issues

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/valuespecification/FunctionExpressionProcessor.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/GenericType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/Parser.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/ParserLibrary.java
legend-pure-core/legend-pure-m3-precisePrimitives/pom.xml
legend-pure-core/legend-pure-m3-precisePrimitives/src/main/java/org/finos/legend/pure/code/core/PlatformPrecisePrimitivesCodeRepositoryProvider.java
legend-pure-core/legend-pure-m3-precisePrimitives/src/main/resources/META-INF/services/org.finos.legend.pure.m3.serialization.filesystem.repository.CodeRepositoryProvider
legend-pure-core/legend-pure-m3-precisePrimitives/src/main/resources/platform_precise_primitives.definition.json
legend-pure-core/legend-pure-m3-precisePrimitives/src/main/resources/platform_precise_primitives/precisePrimitives.pure
legend-pure-core/pom.xml
legend-pure-dsl/legend-pure-dsl-store/legend-pure-m2-dsl-store-grammar/src/main/java/org/finos/legend/pure/m2/inlinedsl/store/processor/RelationStoreAccessorProcessor.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/pom.xml
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/serialization/grammar/v1/RelationalParser.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/TestRelationAccessor.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/incremental/TestRelationDatabaseAccessor.java
pom.xml

Move Precise Primitive to Pure and Fix Relation compile issues

Move Precise Primitive to Pure and Fix Relation compile issues

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractCompiledStateIntegrityTest.java

This change filters the dependencies from the repositories passed to the initialize() method of the compiled state integrity tests. This drastically speeds up the tests as we're only testing the changes for each repository and not re-testing repo's per test class.

Improve performance for CompiledStateIntegrity tests

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/AbstractReferenceIdExtensionTest.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/main/java/org/finos/legend/pure/m2/dsl/mapping/serialization/grammar/v1/processor/AggregationAwareProcessor.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/test/java/org/finos/legend/pure/m2/dsl/mapping/serialization/compiler/reference/v1/TestReferenceIdExtensionV1Mapping.java
legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar/src/test/java/org/finos/legend/pure/m2/dsl/mapping/test/TestAggregationAwareMapping.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/serialization/compiler/reference/v1/TestReferenceIdExtensionV1Relational.java

Fix a bug in AggregationAwareProcessor where the parameter generic types were missing source information.

Fix a bug in AggregationAwareProcessor

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/validation/functionExpression/NewValidator.java

Fix an issue with new validation exceptions where the exceptions list may be loaded from the wrong class loader.

Fix issue with new validation exceptions

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/AbstractTestGeneralizationAtRuntime.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/delta/CodeBlockDeltaCompiler.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/execution/CompiledExecutionSupport.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/execution/CompiledProcessorSupport.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaSourceCodeGenerator.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/ProcessorContext.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/IdBuilder.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/grammar/lang/_enum/ExtractEnumValue.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/grammar/lang/creation/InstantiationHelpers.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CompiledSupport.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/Pure.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/AbstractLazyReflectiveCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/AbstractQuantityCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassLazyImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/measureUnit/MeasureProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/valuespecification/ValueSpecificationProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataAccessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataBuilder.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataEager.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataLazy.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/GraphSerializer.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/binary/DistributedBinaryRepositorySerializer.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/runtime/TestIdBuilder.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/runtime/serialization/TestLazyImplClassifiers.java

Use new reference ids in generated Java code

Use new reference ids in generated Java code

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_Column.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_RelationType.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/relation/TestColumnBuilders.java

Unescape single quotes from column names

Unescape single quotes from column names

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/AssociationProcessor.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/projection/ClassProjectionProcessor.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/compiler/postprocessing/processor/projection/ProjectionUtil.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/GraphTools.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/AbstractReferenceIdExtensionTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/AbstractReferenceTest.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/TestReferenceIdGenerator.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/projection/TestProjectionCompilation.java

Fix source info issues with ClassProjection. Add a projection to the reference id tests.

Fix source info issues with ClassProjection

---

legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/antlr4/org/finos/legend/pure/m2/relational/serialization/grammar/v1/antlr/RelationalParser.g4
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/serialization/grammar/v1/antlr/RelationalGraphBuilder.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/main/java/org/finos/legend/pure/m2/relational/serialization/grammar/v1/processor/ColumnDataTypeFactory.java

Improve Schema DSL

---

legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/delta/CodeBlockDeltaCompiler.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/execution/CompiledProcessorSupport.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/JavaSourceCodeGenerator.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/ProcessorContext.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/IdBuilder.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/grammar/lang/creation/InstantiationHelpers.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/CompiledSupport.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/AbstractLazyReflectiveCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/AbstractQuantityCoreInstance.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/_class/ClassLazyImplProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/type/measureUnit/MeasureProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/valuespecification/ValueSpecificationProcessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataAccessor.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataBuilder.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataEager.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/metadata/MetadataLazy.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/GraphSerializer.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/runtime/TestIdBuilder.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/runtime/serialization/TestLazyImplClassifiers.java

Roll back using new reference ids in generated Java code

Roll back using new reference ids in generated Java code

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/AntlrContextToM3CoreInstance.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/relation/TestColumnBuilders.java

Unescape single quotes in agg column names

Unescape single quotes in agg column names

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/coreinstance/BaseCoreInstance.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/PrimitiveUtilities.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/_class/TestC3Linearization.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/ModelRepository.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/AbstractCoreInstance.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/AbstractCoreInstanceMutableState.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/CoreInstance.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/simple/SimpleCoreInstance.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/simple/SimpleCoreInstanceMutableState.java
legend-pure-core/legend-pure-m4/src/main/java/org/finos/legend/pure/m4/coreinstance/simple/ValueHolder.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/ReflectiveCoreInstance.java

Minor improvements to CoreInstances, including to parsing Integer CoreInstances.

Minor improvements to CoreInstances

---

legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/FunctionExecutionInterpreted.java

Improve qualified property dispatch for interpreted mode by avoiding computing generalizations unless necessary and by not going any higher in generalizations than necessary. Also, avoid recomputing the function type of the original function.

Improve qualified property dispatch for interpreted mode

---

legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar/src/test/java/org/finos/legend/pure/m2/relational/AbstractTestPureDBFunction.java
legend-pure-store/legend-pure-store-relational/legend-pure-runtime-java-extension-compiled-store-relational/src/main/java/org/finos/legend/pure/runtime/java/extension/store/relational/compiled/natives/ResultSetValueHandlers.java

Changes to upgrade h2 version from v1 to v2

H2 v2: Handle floats correctly

---

legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/essentials/meta/type/relation/AddColumns.java

fix relation type cast in AddColumns native function impl

fix relation type cast in AddColumns native function impl

---

legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/io/AbstractTestPrint.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/function/base/lang/AbstractTestRawEvalProperty.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/io/TestPrintCompiled.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/lang/TestRawEvalPropertyCompiled.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/io/TestPrint.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/lang/TestRawEvalProperty.java

removing migrated abstract test classes

Migrate native function tests from legend-engine

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/GenericType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_RelationType.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tests/elements/relation/TestRelationType.java

Fix TypeVariableValues copy

---

.github/workflows/build.yml

Switch from deploy to install for master branch builds, as deploying snapshots currently does not work.

Switch from deploy to install for master branch builds

---

legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/serialization/binary/LazyStringIndex.java

Improve concurrency in LazyStringIndex by eliminating locks and allowing multiple threads to load partitions simultaneously.

Improve concurrency in LazyStringIndex

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/ReferenceIds.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/serialization/compiler/reference/AbstractReferenceIdExtensionTest.java

Fix typos in ReferenceIds and AbstractReferenceIdExtensionTest

Fix typos in reference id code

---

legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/execution/CompiledProcessorSupport.java

Ensure Byte is handled on pure class to java class

Ensure Byte is handled on pure class to java class

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/M3ProcessorSupport.java

Check for null classifiers when given non-existent type path

Check for null classifiers when given non-existent type path

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/window/frame.pure

Introduce FrameNumericValue for range window frame

Introduce FrameNumericValue for range window frame

---

legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/execution/ConsoleCompiled.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/coreinstance/AbstractCompiledCoreInstance.java

Minor improvement to ConsoleCompiled to allow printing to an appendable rather than just building a string.

Minor improvement to ConsoleCompiled

---

legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/test/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/support/function/base/lang/TestFunctionDefinitionModify.java
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/test/java/org/finos/legend/pure/runtime/java/interpreted/function/base/lang/TestFunctionDefinitionModify.java

Move TestFunctionDefinitionModify from legend-engine back to legend-pure

Move TestFunctionDefinitionModify from legend-engine back to legend-pure

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/generictype/GenericType.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/relation/_RelationType.java

Fix isGenericTypeFullyConcrete and isGenericTypeFullyDefined for RelationTypes

Fix isGenericTypeFullyConcrete and isGenericTypeFullyDefined for RelationTypes

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/meta/type/relation/window/frame.pure
legend-pure-runtime/legend-pure-runtime-java-engine-interpreted/src/main/java/org/finos/legend/pure/runtime/java/interpreted/natives/essentials/date/operation/AdjustDate.java
legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-pure/src/main/resources/platform_store_relational/grammar/relational.pure

Introduce FrameIntervalValue metamodel

Introduce FrameIntervalValue metamodel

---

legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/variant/FromJson.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/variant/To.java
legend-pure-runtime/legend-pure-runtime-java-engine-compiled/src/main/java/org/finos/legend/pure/runtime/java/compiled/generation/processors/natives/variant/ToVariant.java
legend-pure-runtime/legend-pure-runtime-java-engine-shared/src/main/java/org/finos/legend/pure/runtime/java/shared/variant/VariantInstanceImpl.java

Make VariantInstanceImpl factory methods backward compatible

Make VariantInstanceImpl factory methods backward compatible

---

legend-pure-core/legend-pure-m3-core/src/main/antlr4/org/finos/legend/pure/m3/serialization/grammar/m3parser/antlr/core/M3CoreParser.g4
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/navigation/graph/GraphPath.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/navigation/graph/TestGraphPath.java

Speed up GraphPath parsing by not using antlr

Speed up GraphPath parsing

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/collection/size/isEmpty.pure
legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/grammar/functions/collection/size/isNotEmpty.pure

Adding test cases for variant isEmpty and isNotEmpty

Variant array isEmpty isNotEmpty tests

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/serialization/compiler/reference/v1/ReferenceIdProviderV1.java
legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/ContainingElementIndex.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tools/TestContainingElementIndex.java

Make ContainingElementIndex public and move it to the tools package

Make ContainingElementIndex public and move it to the tools package

---

legend-pure-core/legend-pure-m3-core/src/main/java/org/finos/legend/pure/m3/tools/ListHelper.java
legend-pure-core/legend-pure-m3-core/src/test/java/org/finos/legend/pure/m3/tools/TestListHelper.java

Add ListHelper.sortAndRemoveDuplicates

Add ListHelper.sortAndRemoveDuplicates

---

legend-pure-core/legend-pure-m3-core/src/main/resources/platform/pure/essential/collection/transformation/removeDuplicates.pure

Updated doc for removeDuplicates and added ordering to tests

removeDuplicates documentation and test ordering

---

legend-pure-core/legend-pure-m3-bootstrap-generator/src/main/java/org/finos/legend/pure/m3/bootstrap/generator/M3ToJavaGenerator.java

Remove duplicate entry in M3ToJavaGenerator.PRIMITIVES

Remove duplicate entry in M3ToJavaGenerator.PRIMITIVES
